### ISSUE TITLE
Caps Lock LED Not Working (macOS Mojave beta)

### ISSUE THREAD

**Issue by jamesstidard** [tekezo/Karabiner-Elements#1502]
Hi,

I have looked through closed issues that look like similar problems to what I'm experiencing, but the fixes in those tickets have not solved the problem for me.

I am using Karabiner-Elements `12.1.0` and while it is running my caps lock LED on my MacBook no longer lights up while it's enabled (it still functions normally though, I just can't tell visually when it's on).

This doesn't appear to be to do with my configuration (as I renamed `~/.config/karabiner` to `~/.config/karabiner.backup`). Though may have to do with me running the public beta version of macOS `10.14 Beta (18A336e)` which may have changed the APIs.

Thanks for the great utility - has let me resurrect my otherwise broken function keys.

**Comment by jamesrobinsonvfx** [comment]
Just started the public beta of macOS Mojave 10.14 Beta (18A336e), and am also experiencing the same caps lock led issue when running Karabiner-Elements.

Also thanks for the tools! It really helps fix the middle-mouse issue in 3d apps.

**Comment by lordalbus** [comment]
I'm facing the same problem. The caps lock light doesn't work when I have Karabiner enabled. Updated to Mojave Beta few days back.

**Comment by johnslemmer** [comment]
I would like to add that the caps lock LED doesn't work in the recently release (non-beta) macos mojave when Karabiner is enabled.

**Comment by marktripney** [comment]
Same

**Comment by oscargong** [comment]
Same here, in Mojave stable build.

**Comment by willihangga** [comment]
same issue, Mojave 18A391

**Comment by sergiuiacob1** [comment]
I subscribe. I am having the same issue, stable MacOS release.

**Comment by srilq** [comment]
Would be great if people put a 👍 on the issue rather than commenting, it's annoying for those subscribed to the thread for status updates.

**Comment by catforce** [comment]
Same here. I just thought only a Mojave issue, but I saw this and quitted Karabiner-Elements, the LED started working and is still not working while running  Karabiner-Elements again.

**Comment by Eisermann** [comment]
The same problems, with all keyboards including apple manufactured :(

**Comment by mwean** [comment]
This might be a different issue, but I'm on a 2018 MBP on High Sierra, and recently my caps lock light has started to "flicker". After I type a shortcut including any of cmd, ctrl, or option, the light turns on for a second and then goes off. I think it's also tied to a brief period where my mappings are disabled, but it's hard to be sure.

**Comment by seansix** [comment]
+ here

**Comment by seansix** [comment]
+1 here

**Comment by kxalex** [comment]
+1

**Comment by jakebathman** [comment]
Hey peeps, if you're here to add `+1` please don't add a new comment. 

**Instead, add 👍 to the bottom of this comment.**

Please only comment if you have additional information about the issue. Every new comment sends those of us subscribed to the thread a new email, and we don't want a bunch of +1's. Thanks!

**Comment by Averethel** [comment]
Subscribing to updates

**Comment by chrstphrchvz** [comment]
> Subscribing to updates

No need to comment, just click the "Subscribe" button on the right, near the beginning of the issue page.

![Subscribe button screenshot](https://help.github.com/assets/images/help/notifications/subscribe_button.png)

**Comment by barisbora** [comment]
+1 here, few seconds ago i updated macbook pro (mid 2015) from 10.13.6 (HighSierra) to 10.14 Mojave and capslock light doest work anymore

**Comment by blesio** [comment]
Confirm that it’s working, great job.

**Comment by gstvomacedo** [comment]
@takezo this latest version also works to I disable the capslock delay?

**Comment by przemekgithub** [comment]
Awesome, works great now

**Comment by harvas77** [comment]
The LED works fine, but the CAPS LOCK delay still persists. A fix would be appreciated soon. Thanks

**Comment by ChrisWeiser** [comment]
Confirmed working. Thank you Fumihiko for the update! You’re awesome!
On Oct 24, 2018, 6:37 AM -0500, harvas77 <notifications@github.com>, wrote:

The LED works fine, but the CAPS LOCK delay still persists. A fix would be appreciated soon. Thanks

**Comment by a-triant** [comment]
All you that confirmed working, you have an Apple keyboard?
I asking because in my case it is still does not working :(
I have a non Apple USB keyboard (Leopold FC750R)

**Comment by blesio** [comment]
I tested on internal keyboard on the 2018 MacBook Pro with Mojave beta

**Comment by ElDeveloper** [comment]
> All you that confirmed working, you have an Apple keyboard?
> I asking because in my case it is still does not working :(
> I have a non Apple USB keyboard (Leopold FC750R)

I can confirm that this bug was solved in the latest beta release. It works on my laptop and with an external keyboard (WASD keyboard).

**Comment by epadillac** [comment]
For me it behaves weird, sometime the led turns off and on by itself :/

**Comment by Gaulomatic** [comment]
Works great now on my Magic Keyboard Space Grey. There is little delay though sometimes, but that's not a big deal. I also tested my (very, very) old Apple Keyboard (the one that is so heavy that you can kill someone with it) - works as well.

**Comment by blesio** [comment]
I was too fast to confirm this is working fine.  It does, but not always.  Seems that Caps Lock does not always turn on, sometimes I need to press it twice.

**Comment by blesio** [comment]
> I was too fast to confirm this is working fine. It does, but not always. Seems that Caps Lock does not always turn on, sometimes I need to press it twice.

But then again I might have an issue with the Caps Lock button, seems that by disabling and removing the app I still have the same behavior. Oh well....

**Comment by a-triant** [comment]
Today I have updated to 12.1.53, the Caps Lock LED still does not work, same as wrote in previous message.

**Comment by bobvandevijver** [comment]
> I was too fast to confirm this is working fine. It does, but not always. Seems that Caps Lock does not always turn on, sometimes I need to press it twice.

I still have that, but that is not related to this issue or to Mojave, as I already had that with earlier versions. Sometimes, pressing capslock simple doesn't work at all, sometimes the led blinks with the all-caps keys presses.

**Comment by JohnPeacockMessageSystems** [comment]
Installed the beta and the capslock light does not come on with DasKeyboard (non-Mac version). Still running High Sierra 10.13.6 (IT has not approved Mojave yet).

**Comment by tekezo** [comment]
You have to enable LED control manually on Devices tab if you are using non-Apple keyboard.

![181026-0001](https://user-images.githubusercontent.com/659178/47575500-3057cd00-d97d-11e8-865a-fc3ac861d7ac.png)

**Comment by gstvomacedo** [comment]
@takezo will you add back the option of capslock delay?

**Comment by hihell** [comment]
@takezo I ticked the box but LED still not working, I'm using the microsoft ergonomic keyboard

**Comment by TheRealPOTUS** [comment]
Issue was resolved for me in 12.1.55 update.

**Comment by pravic** [comment]
> The LED works fine, but the CAPS LOCK delay still persists.

I am experiencing not a delay per se, but a missed press from time to time.

**Comment by ilovebamboo** [comment]
i have dell km 717 keyboard but caps lock led don't light,
<img width="1000" alt="qq20181118-103420 2x" src="https://user-images.githubusercontent.com/6214084/48667970-87d0ff00-eb1d-11e8-939d-84d6c23ff9d2.png">

**Comment by msogrin** [comment]
I have a Filco Convertible 2 TKL keyboard, and Caps LED doesn't work on Mojave and Karabiner 12.1.56.

![image](https://user-images.githubusercontent.com/9539622/48703325-37c06e00-ebeb-11e8-92f8-171c4534cfc9.png)

**Comment by momodupi** [comment]
The Caps LED lights after clicking the Caps button, but all the complex modifications don't work while the LED is lighting.

**Comment by n1x0id** [comment]
I have apple usb keyboard, Mojave and 12.1.56 version (beta) and my caps lock led don't work

**Comment by clarkwang** [comment]
Same issue for me with `Mojave`. I thought it is a macOS problem. I'm using the `Macbook Air`'s builtin keyboard.

**Comment by silviorelli** [comment]
> I have apple usb keyboard, Mojave and 12.1.56 version (beta) and my caps lock led don't work.
> ![45348057544_ccdddaceec_o](https://user-images.githubusercontent.com/4451377/49078547-5f4cb180-f24f-11e8-943b-5a0745f54955.jpg)
> <img alt="2018-11-27 14 15 59" width="1112" src="https://user-images.githubusercontent.com/4451377/49078554-64116580-f24f-11e8-93ef-f2529cf91749.png">
> <img alt="2018-11-27 14 16 05" width="1112" src="https://user-images.githubusercontent.com/4451377/49078557-67a4ec80-f24f-11e8-857f-0b307d10cdcc.png">

Similar situation, but the keyboard has the italian layout.
The 12.1.56 beta version fixed the issue for me.
Cheers!

**Comment by Reconed** [comment]
Had the same. New Beta Krabinier Elelments fixes that issue

**Comment by masterandrey** [comment]
> I fixed this issue at the latest beta version. (v12.1.51)
> 
> You can get it from "Check for beta updates" button.
> https://pqrs.org/osx/karabiner/document.html#check-for-updates

In fact I had to upgrade from 12.1.55 to beta 12.1.56 and now it works again

**Comment by alxgarza** [comment]
Apple Extended Keyboard with iMate on Mojave (10.14.2) with Karabiner-Elements (12.1.57) Caps Light does not work.

**Comment by jonobrown** [comment]
Me too, Caps Lock light was lit up, now does not go on at all

**Comment by nikolaydimitrov** [comment]
I have the latest version (12.1.0) and using the internal keyboard, but the Caps Lock LED doesn't turn on and off.
Upgraded to Mojave uninstalled the old Karabiner and installed fresh one.

**Comment by quackenbush** [comment]
FYI, this is fixed in the beta version 12.1.59 for me, using Macbook Air.

To upgrade to the beta version  go to Preferences => Misc => Check for beta updates (right side button).

**Comment by nikolaydimitrov** [comment]
@quackenbush thanks a lot! Didn't think about beta. Works now!

**Comment by iofik** [comment]
God bless whoever fixed this.
The bug was really annoying.

**Comment by alxgarza** [comment]
Upgraded to Karabiner 23.1.59 and it is still not working for me. Caps Lock  Led is always off.

**Comment by jpark2320** [comment]
I was having the same issue. For me, I unchecked [Apple Internal Keyboard / Trackpad] and now the caps lock light toggles.

![screen shot 2019-01-19 at 8 59 52 pm](https://user-images.githubusercontent.com/19990742/51435508-709db300-1c2d-11e9-85b1-0034ce392855.png)

**Comment by alxgarza** [comment]
I have tried all combinations and the leds don’t work.

This is my curren configuration:

**Comment by DarinDev1000** [comment]
Go to Karabiner-Elements>Preferences>Devices and turn off Manipulate LED for the default keyboard.

**Comment by Splaktar** [comment]
Just got the `12.2.0` update today and this is fixed. Thank you!

I wish that I had found this issue before and got in on the fix in beta months ago.

**Comment by alxgarza** [comment]
It is still not working on Apple Extended Keyboard with iMate on Mojave (10.14.3) with Karabiner-Elements (12.2.0) Caps Light does not work. And Caps do not say do not work.  Even thou the cap_lock event is showing in the event window.

**Comment by msogrin** [comment]
> I have a Filco Convertible 2 TKL keyboard, and Caps LED doesn't work on Mojave and Karabiner 12.1.56.
> 
> ![image](https://user-images.githubusercontent.com/9539622/48703325-37c06e00-ebeb-11e8-92f8-171c4534cfc9.png)

It is still not working with version 12.2.0.

**Comment by muthukumarn** [comment]
Caps lock works with Mojave 10.14.2 (18C54) with Karabiner-Elements (12.2.0)

**Comment by alxgarza** [comment]
It does not work with all keyboards.

**Comment by msogrin** [comment]
> I have a Filco Convertible 2 TKL keyboard, and Caps LED doesn't work on Mojave and Karabiner 12.1.56.
> 
> ![image](https://user-images.githubusercontent.com/9539622/48703325-37c06e00-ebeb-11e8-92f8-171c4534cfc9.png)

Still doesn't work. Karabiner 12.2.11 is installed now.

**Comment by ejjoo** [comment]
bump

**Comment by ejjoo** [comment]
I have Filco Majestouch 2, still not working. version 1.9 and Mojave 10.14.5

**Comment by peterflynn** [comment]
Upgrading from Karabiner 12.1.0 to 12.5.0 fixed this for me, but it didn't fix another (related?) issue I've been having: _sometimes_, I have to hit Caps Lock twice before it will toggle on.  This isn't just the light, but the actual "typing in uppercase" functionality, too.  It seems completely random whether it will take two or one keypress to enable Caps Lock.

Is anyone else experiencing that?  I couldn't find any other Karabiner bugs on that issue...

**Comment by no7dw** [comment]
after upgrade to Catalina, same happened here.
[Reset NVRAM or PRAM on your Mac](https://support.apple.com/en-us/HT204063)
got fixed after repeat the process for  **second** times

**Comment by fxh90** [comment]
After upgrade to Catalina, caps lock LED was always on.
After reset NVRAM once, got fixed.

**Comment by tominabox1** [comment]
Running a few QMK keyboards on a hackintosh and none of them have working caps LEDs under the latest Catalina public release, reset nvram a few times and still no change. Ticked LED box in Karabiner off and on, neither seemed to make any difference. LEDs work in Windows.
