### ISSUE TITLE
Key "stuck"

### ISSUE THREAD

**Issue by gevro** [tekezo/Karabiner-Elements#1828]
Since the last update, every few hours suddenly there is some key that is constantly being inputted even though I am not pressing any keys on the keyboard. I have to restart the computer because I can't do anything. Not clear what key it is since I cannot open Karabiner event viewer to see it. Must be some major new bug....

**Comment by tanuva** [comment]
I *think* I see the same problem in KE 12.2.0. The system feels like a key is hanging *and* one key switched to just producing a letter on key-up instead of key-down. (That would be 'g' (keycap label) or 'o' (letter in keyboard layout) respectively for me.)

In the Log view of KE I see that `grabber_client` is constantly restarting:
```
[2019-04-29 11:44:36.880] [info] [observer] grabber_client is closed.
[2019-04-29 11:44:37.880] [info] [observer] grabber_client is connected.
[2019-04-29 11:44:37.882] [info] [observer] grabber_client is closed.
[2019-04-29 11:44:38.953] [info] [observer] grabber_client is connected.
[2019-04-29 11:44:38.957] [info] [observer] grabber_client is closed.
[2019-04-29 11:44:39.957] [info] [observer] grabber_client is connected.
[2019-04-29 11:44:39.959] [info] [observer] grabber_client is closed.
[2019-04-29 11:44:41.000] [info] [observer] grabber_client is connected.
[2019-04-29 11:44:41.003] [info] [observer] grabber_client is closed.
```

I managed to beat my keyboard into submission for the time being with a combination of restarting KE, switching to a profile with no modifications active and disabling KE for my keyboard in the Devices tab. Now it works again with modifications turned on as it should, but I can't tell for sure which change "fixed" it.
The constant `grabber_client` restarts are still there though.

Background info:
- macOS 10.14.4
- The last thing I changed is to switch off the KE menu bar icon, making it run in "daemon mode".
- Just in case: I have KE running in two user accounts on the same machine (work/home via fast user switching)
- The "complex modifications" for the Neo 2.0 layout are active

**Comment by tekezo** [comment]
@tanuva Thank you for your log.
Are your log messages reproduced even with the latest release (v12.3.0)?

**Comment by cpannwitz** [comment]
Same problem. 
- 10.14.4 macOS, MBPro, Karabiner Elements v12.3.0
Happens only after opening up the MacBook, without (re)starting.

Fixed by restarting the MacBook or quitting Karabiner Elements.

**Comment by tanuva** [comment]
> @tanuva Thank you for your log.
> Are your log messages reproduced even with the latest release (v12.3.0)?

After I got the problem to go away yesterday I updated to 12.3.0. So far it keeps working fine. However the issue also came up rather spontaneously - if I see it happen again, I'll report back.
Is there any further logging that would be good to collect in case it happens again?

**Comment by tekezo** [comment]
@tanuva 
The following files contains complete log messages if you can collect them.

- /var/log/karabiner/grabber.log
- /var/log/karabiner/observer.log
- ~/.local/share/karabiner/log/console_user_server.log

If you don't know how to collect them, please show me log messages on `Karabiner-Elements Preferences > Log tab` which includes most messages.

**Comment by FryJay** [comment]
I'm seeing this issue as well.  Sometimes it's a modifier key but more often it's a random key that I must have pressed at the time.  I started noticing the issue after I did a full reinstall of my laptop a couple of weeks ago so I think it must be a recent update that caused it.

**Comment by gevro** [comment]
So far, it seems to me that if I wake up my computer only with my mouse and not with my keyboard, the issue doesn't happen. I will update if anything changes.

**Comment by pezely** [comment]
Similar issue same day as having upgraded to 12.3.0, also after cold boot: 

Modifier keys occasionally/intermittently cease working or possibly gets augmented as if another modifier key had been pressed.

For instance, pressing Control behaves as if Shift had been pressed along with it. (I have Control and Fn swapped, and changed Right Option remapped as Right Control; both Control keys were impacted.)

Snippets of requested log files beginning with final mention of v12.2.0:

- [console_user_server.log](https://github.com/tekezo/Karabiner-Elements/files/3133049/console_user_server.log)
- [grabber.log](https://github.com/tekezo/Karabiner-Elements/files/3133050/grabber.log)
- [observer.log](https://github.com/tekezo/Karabiner-Elements/files/3133051/observer.log)

Running on macOS 10.13.6 (17G6030), MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports), 2.3 GHz Intel Core i5, 8 GB 2133 MHz LPDDR3

**Comment by gevro** [comment]
I don't see anything abnormal in my logs when this happens. Note that this appears to be the same as issue #466 .

**Comment by gevro** [comment]
This is happening about 2-3 times a day. It is very frustrating. Is there any answer why this major bug is happening?

**Comment by prodeveloper0** [comment]
This issue is occurred with the logs below.

[2019-05-02 17:26:27.572] [warning] [grabber] Designer Keyboard (device_id:4294970970) is not observed yet. Please wait for a while.
[2019-05-02 17:26:27.629] [info] [observer] matching device:
[2019-05-02 17:26:27.629] [info] [observer]   registry_entry_id: 4294970970
[2019-05-02 17:26:27.629] [info] [observer]   manufacturer: Microsoft
[2019-05-02 17:26:27.629] [info] [observer]   product: Designer Keyboard
[2019-05-02 17:26:27.629] [info] [observer]   vendor_id: 1118
[2019-05-02 17:26:27.629] [info] [observer]   product_id: 2054
[2019-05-02 17:26:27.629] [info] [observer]   location_id: 0x445b9a40
[2019-05-02 17:26:27.629] [info] [observer]   is_keyboard: true
[2019-05-02 17:26:27.629] [info] [observer]   is_pointing_device: false
[2019-05-02 17:26:27.629] [warning] [grabber] Designer Keyboard (device_id:4294970970) is ungrabbable temporarily by a failure of accessing device.
[2019-05-02 17:26:27.639] [info] [observer] Designer Keyboard (device_id:4294970970) is observed.
[2019-05-02 17:26:27.646] [info] [grabber] Designer Keyboard (device_id:4294970970) is grabbed.
[2019-05-02 17:26:27.740] [info] [grabber] first grabbed event: device_id:4294970970 time_stamp:11977189251418

**Comment by UkiahSmith** [comment]
I am experiencing this same issue. 

A couple of days ago the Cmd-Shift-P combination was being activated on repeat. 

Today the _t_ key is on repeat. It seems to be "held down". When I switch application it continues in the background on the original application but not the current app. When I switch back it sometimes stop, sometimes continues to hold the _t_ key. I quit Karabiner and it stopped. 

Here are the logs from today.

```
[2019-04-29 07:31:14.845] [info] [console_user_server] version 12.3.0
[2019-04-29 07:31:15.307] [info] [console_user_server] karabiner_grabber_alerts.json is updated.
[2019-04-29 07:31:15.530] [info] [console_user_server] receiver is initialized
[2019-04-29 07:31:15.531] [info] [console_user_server] grabber_client is started.
[2019-04-29 07:31:15.531] [info] [console_user_server] grabber_client is connected.
[2019-04-29 07:31:15.537] [info] [console_user_server] Load /Users/user/.config/karabiner/karabiner.json...
[2019-04-29 07:31:15.539] [info] [console_user_server] core_configuration is updated.
[2019-04-29 07:31:15.764] [info] [console_user_server] Check for updates...
[2019-04-29 08:24:50.651] [info] [console_user_server] version 12.3.0
[2019-04-29 08:24:50.712] [info] [console_user_server] karabiner_grabber_alerts.json is updated.
[2019-04-29 08:24:50.797] [info] [console_user_server] receiver is initialized
[2019-04-29 08:24:50.798] [info] [console_user_server] grabber_client is started.
[2019-04-29 08:24:50.799] [info] [console_user_server] grabber_client is connected.
[2019-04-29 08:24:50.805] [info] [console_user_server] Load /Users/user/.config/karabiner/karabiner.json...
[2019-04-29 08:24:50.809] [info] [console_user_server] core_configuration is updated.
[2019-04-29 08:24:51.085] [info] [console_user_server] Check for updates...
[2019-04-29 16:09:17.446] [info] [console_user_server] version 12.3.0
[2019-04-29 16:09:17.696] [info] [console_user_server] karabiner_grabber_alerts.json is updated.
[2019-04-29 16:09:17.946] [info] [console_user_server] receiver is initialized
[2019-04-29 16:09:17.948] [info] [console_user_server] grabber_client is started.
[2019-04-29 16:09:17.949] [info] [console_user_server] grabber_client is connected.
[2019-04-29 16:09:17.953] [info] [console_user_server] Load /Users/user/.config/karabiner/karabiner.json...
[2019-04-29 16:09:17.955] [info] [console_user_server] core_configuration is updated.
[2019-04-29 16:09:18.139] [info] [console_user_server] Check for updates...
[2019-05-02 07:38:32.465] [info] [console_user_server] version 12.3.0
[2019-05-02 07:38:32.706] [info] [console_user_server] karabiner_grabber_alerts.json is updated.
[2019-05-02 07:38:33.050] [info] [console_user_server] receiver is initialized
[2019-05-02 07:38:33.051] [info] [console_user_server] grabber_client is started.
[2019-05-02 07:38:33.052] [info] [console_user_server] grabber_client is connected.
[2019-05-02 07:38:33.057] [info] [console_user_server] Load /Users/user/.config/karabiner/karabiner.json...
[2019-05-02 07:38:33.060] [info] [console_user_server] core_configuration is updated.
[2019-05-02 07:38:33.274] [info] [console_user_server] Check for updates...
```

I feel like I experienced something similar a few months ago, but only once or twice, and then it went away. Now it seems more frequent.

**Comment by bojankseneman** [comment]
I am affected by this issue too, downgrading back to the good old 12.1.0

**Comment by gevro** [comment]
@bojankseneman - let us know if downgrading to 12.1.0 fixes the issue?

**Comment by bojankseneman** [comment]
Yes I was using 12.1.0 as the 12.2.0 broke the backlight issue which is fixed in 12.3.0 but I get this issue now. So I am going back to 12.1.0. The only thing that doesn't work for me in 12.1.0 is CAPS LOCK LED indicator, which I don't really mind.

**Comment by gevro** [comment]
@bojankseneman Just to clarify - did going back to 12.1.0 fix the stuck repeating key issue?

**Comment by karolwojciszko** [comment]
I am experiencing this same issue ;/
mac 10.14.4, KE: 12.3

**Comment by ClumsyLee** [comment]
Same issue macOS 10.14.3 (18D109), KE 12.3.0, downgrading to 12.2.0 solves the issue.

**Comment by prohtex** [comment]
Same here, for me the command key is stuck. This was happening about a year ago with a much earlier version of KE. Sorry to see it is back. It is a complete nightmare and disabling KE doesn't work - you have to restart. Only long term solution is to uninstall.

**Comment by matthewadams** [comment]
Me too.  Downgraded to 12.1.0 to see if that helps.  Also submitted a bug report (suggestion) to macOS category requesting that they bring Karabiner's capabilities directly into macOS.  I doubt anyone can view it, but here's the issue link:  https://bugreport.apple.com/web/?problemID=50443488.  FYI, here's the description I entered (along with two screenshots):

Area:
Keyboards, mice and trackpads

I've used Karabiner Elements (https://pqrs.org/osx/karabiner/) for years now, but every time there's a macOS update (10.14.4 in this case), it seems to break Karabiner Elements.  I'm tired of not having an Apple-supported, native macOS means of remapping keystrokes, especially after having spent around $4000 on a MacBook Pro in 2012, and then again 2019.

For accessibility reasons, I use a Microsoft Surface ergonomic keyboard (see https://www.amazon.com/gp/product/B01MFCTRZM).  I simply would like to remap the left Alt key to Apple's left Command key, the left Windows key to Apple's Option key, and same for the right Alt & Windows keys.  A more general solution, however, would be to allow arbitrary key remappings.

In the Keyboard system preferences pane, if you select the Keyboard tab, then click the "Modifier Keys..." button, a dialog pops up that lets you remap only 4 keys:  Caps Lock, Control, Option & Command.  The problem is, if I remap Option to Command and Command to Option, I do not get the desired behavior on the Microsoft Surface keyboard, only on my MacBook Pro's keyboard.

Please expand that dialog to allow the remapping of any keystroke to any other keystroke, and make the remappings specific to each keyboard device, so that I can have multiple keyboards each with their own key remappings.

Please listen to a paying customer who has taken the time to issue a reasonable and thorough issue, and provide an Apple-supported equivalent of Karabiner Elements.

**Comment by bojankseneman** [comment]
@matthewadams good luck with that :)

**Comment by gevro** [comment]
Downgrading to KE 12.2.0 appears to prevent the issue for me too.

**Comment by matthewadams** [comment]
@gevro I downgraded to 12.1.0.  The only symptom I've seen is that the Magic Mouse 2 sometimes get into a state where the mouse pointer will only move vertically, not horizontally.  It's a transient condition that corrects itself after seconds to a minute or so.  I guess I'll try 12.2.0.

**Comment by prodeveloper0** [comment]
I think this problem might be occurred with energy-saving featured HID or Bluetooth HID

**Comment by prohtex** [comment]
> I think this problem might be occurred with energy-saving featured HID or Bluetooth HID
Oh definitely 🙄

**Comment by dakshj** [comment]
I see this issue about twice a day since I updated to 12.3.0. Attaching my log files from `/var/log/karabiner`.
[grabber.log](https://github.com/tekezo/Karabiner-Elements/files/3160544/grabber.log)
[observer.log](https://github.com/tekezo/Karabiner-Elements/files/3160547/observer.log)

**Comment by yahmez00** [comment]
Can also confirm I am getting this issue. Disconnecting the bluetooth and turning it back on again seems to resolve it (using a Microsoft bluetooth keyboard).

**Comment by tekezo** [comment]
Thanks for all feedbacks!

I've fixed this issue at v12.3.5.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

## Important

The key stuck issue might occur at the latest beta version.
(We cannot completely remove the key stuck issue until an macOS key handling issue is fixed.)

Please press the stuck key again if you faced the issue with the latest beta version.
The state will be fixed.

You can confirm the stuck key information in the log as follows.

```
[2019-05-11 05:04:44.065] [warning] [grabber] XXX (device_id:4294990687) is ungrabbable
temporarily until {"key_code":"left_shift"} is pressed again.
```

## Detail

The issue occurs in any of the following cases.

- When you hold down a key at login.
- When you hold down a key at wake up.
- When you hold down a key just after the keyboard is connected.

This issue is caused by both Karabiner-Elements issue and macOS issue.
The stuck issue is essentially caused by macOS issue and we cannot avoid it.
(macOS does not release keys which are pressed before Karabiner-Elements grabs the keyboard.)

Karabiner-Elements has a workaround to avoid the macOS issue, however, a problem has been introduced into the workaround at v12.3.0.

This problem is related with the following issue that has been fixed at v12.3.0.

> Added a wait before grabbing device in order to avoid an macOS issue that device will be unusable after Karabiner-Elements is quit.

The `wait` increases the accident rate of this issue, so the key stuck happen frequently after v12.3.0 update.
But reduce the wait as v12.2.0, the fixed above issue happen again :-(

**Comment by chinigo** [comment]
Thank you for your quick fix, @tekezo!

**Comment by tekezo** [comment]
Notification window is introduced since v12.3.11.
<img width="436" alt="Screen Shot 2019-05-14 at 3 23 58" src="https://user-images.githubusercontent.com/659178/57645726-e32a0880-75f9-11e9-990e-929f4bf8faa2.png">

**Comment by bojankseneman** [comment]
Looks like the v12.3.11 works ok for me :) Thx

**Comment by alok** [comment]
macOS 10.14.5 was just released. Does anyone know if that fixed the underlying issue?

**Comment by matthewadams** [comment]
FYI, here is Apple's response to my request for them to allow arbitrary key remappings in macOS.  They basically said, "Naw, we're not going to do that."
```
There are no plans to address this.

We are now closing this report.

If you have questions about the resolution, or if this is still a critical issue for you, then please update your bug report with that information.

Please be sure to regularly check new Apple releases for any updates that might affect this issue.
```

**Comment by thomasthebaker** [comment]
Thanks for the fixes that have already been made. I think there may still be an issue although it is better than before.

I was having the key repeat issue frequently on 12.3.0 and moved to 12.4.0 yesterday. It was ok for a while but just happened on 12.4.0. 

Here's log snippet, I think the keyboard might have been terminated because it's bluetooth so probably disconnects when idle. I tried logging in at 12:18:21 after being away for 15 mintues and then I had the key repeat issue. I pulled the batteries from the keyboard to disconnect it at which point the key repeat stopped happening:

```
[2019-05-15 10:22:41.166] [info] [grabber] mouse_key_xy_scale: 100
[2019-05-15 12:02:49.980] [info] [observer] device_id:4294971561 is terminated.
[2019-05-15 12:02:49.980] [info] [observer] rescan devices...
[2019-05-15 12:02:49.980] [info] [grabber] Ergonomic Keyboard (device_id:4294971561) is terminated.
[2019-05-15 12:02:49.980] [info] [grabber] Magic Trackpad 2 (device_id:4294968941) is ignored.
[2019-05-15 12:18:21.832] [info] [observer] matching device:
[2019-05-15 12:18:21.832] [info] [observer]   registry_entry_id: 4294971953
[2019-05-15 12:18:21.832] [info] [observer]   manufacturer: Microsoft
[2019-05-15 12:18:21.832] [info] [observer]   product: Ergonomic Keyboard
[2019-05-15 12:18:21.832] [info] [observer]   vendor_id: 1118
[2019-05-15 12:18:21.832] [info] [observer]   product_id: 2071
[2019-05-15 12:18:21.832] [info] [observer]   location_id: 0x9a30c84
[2019-05-15 12:18:21.832] [info] [observer]   is_keyboard: true
[2019-05-15 12:18:21.832] [info] [observer]   is_pointing_device: false
[2019-05-15 12:18:21.832] [info] [observer] rescan devices...
[2019-05-15 12:18:21.833] [info] [grabber] Ergonomic Keyboard (device_id:4294971953) is grabbed.
[2019-05-15 12:19:10.203] [info] [observer] device_id:4294971953 is terminated.
[2019-05-15 12:19:10.203] [info] [observer] rescan devices...
[2019-05-15 12:19:10.203] [info] [grabber] Ergonomic Keyboard (device_id:4294971953) is terminated.
[2019-05-15 12:19:10.203] [info] [grabber] Magic Trackpad 2 (device_id:4294968941) is ignored.
[2019-05-15 12:26:00.476] [info] [observer] device_id:4294969089 is terminated.
[2019-05-15 12:26:00.477] [info] [observer] rescan devices...
[2019-05-15 12:26:00.775] [info] [console_user_server] version 12.2.0
```

Earlier in the day I saw the notification window that you introduced and didn't get the key repeat issue:
```
[2019-05-15 09:58:05.404] [info] [grabber] Ergonomic Keyboard (device_id:4294971474) is terminated.
[2019-05-15 09:58:05.405] [info] [observer] rescan devices...
[2019-05-15 09:58:05.405] [info] [grabber] Magic Trackpad 2 (device_id:4294968941) is ignored.
[2019-05-15 10:13:55.843] [info] [observer] matching device:
[2019-05-15 10:13:55.843] [info] [observer]   registry_entry_id: 4294971561
[2019-05-15 10:13:55.843] [info] [observer]   manufacturer: Microsoft
[2019-05-15 10:13:55.843] [info] [observer]   product: Ergonomic Keyboard
[2019-05-15 10:13:55.843] [info] [observer]   vendor_id: 1118
[2019-05-15 10:13:55.843] [info] [observer]   product_id: 2071
[2019-05-15 10:13:55.843] [info] [observer]   location_id: 0x9a30c84
[2019-05-15 10:13:55.843] [info] [observer]   is_keyboard: true
[2019-05-15 10:13:55.843] [info] [observer]   is_pointing_device: false
[2019-05-15 10:13:55.843] [info] [observer] rescan devices...
[2019-05-15 10:13:55.849] [info] [observer] Ergonomic Keyboard (device_id:4294971561) is observed.
[2019-05-15 10:13:55.849] [info] [grabber] Ergonomic Keyboard (device_id:4294971561) is grabbed.
[2019-05-15 10:13:55.908] [warning] [grabber] Ergonomic Keyboard (device_id:4294971561) is ignored temporarily until {"key_code":"t"} is pressed again.
[2019-05-15 10:13:55.908] [info] [grabber] Ergonomic Keyboard (device_id:4294971561) is ungrabbed.
[2019-05-15 10:19:39.381] [info] [grabber] Ergonomic Keyboard (device_id:4294971561) is grabbed.
```

**Comment by WuTheFWasThat** [comment]
Just wanted to add - I'd been hitting this issue *very* reliably prior to v12.3.5.  After the update, I've still seen it, but at a much reduced frequency.  I've had bluetooth disabled, so it can still happen regardless of that.

**Comment by tekezo** [comment]
@thomasthebaker Thank you for feedback!

The key repeat issue still happen due to macOS issue, however, you can stop the key repeat by pressing the repeated key again.
If not stopped, I guess the issue occured by macOS or hardware problem.
Please tell me if you find the detailed way to reproduce this issue.

> I saw the notification window

The notification window is always opened when you held down a key before Karabiner-Elements opens the device.
Therefore, the window may be open even when key is not repeated.
(We cannot know whether key is repeated or not since macOS does not provide API, so we always have to open the window.)

**Comment by nathanjd** [comment]
I am on 12.4.0 and continue to have both issues as described by @thomasthebaker.

1. Key gets stuck repeating. Have to pull batteries to stop. This happens ~5 times a day for me.
2. Window notification for ignored keys happens multiple times per hour.

OS X Mojave 10.14.4 (18E227)
Surface Ergonomic Keyboard (bluetooth)

https://www.microsoft.com/en-us/p/surface-ergonomic-keyboard/90PNC9LJWPX9/5Z3V

Here are the logs. Not sure if they go back to when the repeat happened though there are plenty of instances of the ignored notification. I'll post more logs if I can confirm they demonstrate the incessant repeat.

```
[2019-05-15 16:47:56.072] [info] [observer]   manufacturer: Microsoft
[2019-05-15 16:47:56.072] [info] [observer]   product: Ergonomic Keyboard
[2019-05-15 16:47:56.072] [info] [observer]   vendor_id: 1118
[2019-05-15 16:47:56.072] [info] [observer]   product_id: 2071
[2019-05-15 16:47:56.072] [info] [observer]   location_id: 0x12e70df9
[2019-05-15 16:47:56.072] [info] [observer]   is_keyboard: true
[2019-05-15 16:47:56.072] [info] [observer]   is_pointing_device: false
[2019-05-15 16:47:56.072] [info] [grabber] Ergonomic Keyboard (device_id:4294999273) is grabbed.
[2019-05-15 16:47:56.074] [info] [observer] rescan devices...
[2019-05-15 17:01:10.690] [info] [observer] device_id:4294999273 is terminated.
[2019-05-15 17:01:10.690] [info] [grabber] Ergonomic Keyboard (device_id:4294999273) is terminated.
[2019-05-15 17:01:10.691] [info] [observer] rescan devices...
[2019-05-15 17:01:10.692] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294997677) is ignored.
[2019-05-15 17:01:10.693] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294997523) is ignored.
[2019-05-15 17:01:10.693] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294997517) is ignored.
[2019-05-15 17:01:10.693] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294984914) is ignored.
[2019-05-15 17:11:54.468] [info] [observer] matching device:
[2019-05-15 17:11:54.468] [info] [observer]   registry_entry_id: 4295000062
[2019-05-15 17:11:54.468] [info] [observer]   manufacturer: Microsoft
[2019-05-15 17:11:54.468] [info] [observer]   product: Ergonomic Keyboard
[2019-05-15 17:11:54.468] [info] [observer]   vendor_id: 1118
[2019-05-15 17:11:54.468] [info] [observer]   product_id: 2071
[2019-05-15 17:11:54.468] [info] [observer]   location_id: 0x12e70df9
[2019-05-15 17:11:54.469] [info] [observer]   is_keyboard: true
[2019-05-15 17:11:54.469] [info] [observer]   is_pointing_device: false
[2019-05-15 17:11:54.469] [info] [observer] rescan devices...
[2019-05-15 17:11:54.480] [info] [grabber] Ergonomic Keyboard (device_id:4295000062) is grabbed.
[2019-05-15 17:11:54.504] [warning] [grabber] Ergonomic Keyboard (device_id:4295000062) is ignored temporarily until {"key_code":"g"} is pressed again.
[2019-05-15 17:11:54.505] [info] [grabber] Ergonomic Keyboard (device_id:4295000062) is ungrabbed.
[2019-05-15 17:11:54.559] [info] [observer] Ergonomic Keyboard (device_id:4295000062) is observed.
[2019-05-15 17:11:54.594] [warning] [grabber] Ergonomic Keyboard (device_id:4295000062) is ignored temporarily until {"key_code":"g"} is pressed again.
[2019-05-15 17:11:56.927] [info] [grabber] Ergonomic Keyboard (device_id:4295000062) is grabbed.
[2019-05-15 20:09:44.762] [error] [grabber] console_user_server_client error: Connection reset by peer
[2019-05-15 20:09:44.763] [info] [grabber] console_user_server_client is closed. (uid:600708325)
[2019-05-15 20:09:44.765] [info] [grabber] event_tap_monitor terminated
[2019-05-15 20:09:44.770] [info] [observer] device_id:4294969785 is terminated.
[2019-05-15 20:09:44.770] [info] [grabber] virtual_hid_device_client is closed.
[2019-05-15 20:09:44.771] [info] [observer] rescan devices...
[2019-05-15 20:09:44.771] [info] [grabber] device_grabber is stopped.
[2019-05-15 20:09:46.936] [info] [observer] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294984911) is observed.
[2019-05-15 20:09:56.048] [info] [grabber] current_console_user_id: none
[2019-05-15 20:09:56.049] [info] [grabber] receiver is terminated
[2019-05-15 20:09:56.049] [info] [grabber] receiver is initialized
[2019-05-16 09:40:58.686] [info] [grabber] version 12.4.0
[2019-05-16 09:40:58.688] [info] [grabber] /sbin/kextload '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext'
[2019-05-16 09:40:59.527] [info] [observer] version 12.4.0
[2019-05-16 09:40:59.533] [info] [observer] device_observer is started.
[2019-05-16 09:40:59.533] [info] [observer] grabber_client is started.
[2019-05-16 09:41:00.766] [info] [grabber] kextload exit status: 0
[2019-05-16 09:41:00.772] [info] [grabber] current_console_user_id: none
[2019-05-16 09:41:00.773] [info] [grabber] receiver is initialized
[2019-05-16 09:41:01.640] [info] [observer] grabber_client is connected.
[2019-05-16 09:41:01.640] [info] [observer] rescan devices...
[2019-05-16 09:41:02.610] [info] [observer] matching device:
[2019-05-16 09:41:02.745] [info] [observer]   registry_entry_id: 4294968365
[2019-05-16 09:41:02.745] [info] [observer]   manufacturer: Microsoft
[2019-05-16 09:41:02.745] [info] [observer]   product: Microsoft® 2.4GHz Transceiver v9.0
[2019-05-16 09:41:02.745] [info] [observer]   vendor_id: 1118
[2019-05-16 09:41:02.745] [info] [observer]   product_id: 1957
[2019-05-16 09:41:02.745] [info] [observer]   location_id: 0x14500000
[2019-05-16 09:41:02.745] [info] [observer]   is_keyboard: true
[2019-05-16 09:41:02.745] [info] [observer]   is_pointing_device: false
[2019-05-16 09:41:02.746] [info] [observer] rescan devices...
[2019-05-16 09:41:02.746] [info] [observer] matching device:
[2019-05-16 09:41:02.746] [info] [observer]   registry_entry_id: 4294968215
[2019-05-16 09:41:02.746] [info] [observer]   product: Apple Internal Keyboard / Trackpad
[2019-05-16 09:41:02.746] [info] [observer]   vendor_id: 1452
[2019-05-16 09:41:02.746] [info] [observer]   product_id: 632
[2019-05-16 09:41:02.746] [info] [observer]   location_id: 0x1000000
[2019-05-16 09:41:02.747] [info] [observer]   is_keyboard: true
[2019-05-16 09:41:02.747] [info] [observer]   is_pointing_device: false
[2019-05-16 09:41:02.749] [info] [observer] rescan devices...
[2019-05-16 09:41:02.749] [info] [observer] matching device:
[2019-05-16 09:41:02.749] [info] [observer]   registry_entry_id: 4294968221
[2019-05-16 09:41:02.750] [info] [observer]   product: Apple Internal Keyboard / Trackpad
[2019-05-16 09:41:02.750] [info] [observer]   vendor_id: 1452
[2019-05-16 09:41:02.750] [info] [observer]   product_id: 632
[2019-05-16 09:41:02.750] [info] [observer]   location_id: 0x1000000
[2019-05-16 09:41:02.750] [info] [observer]   is_keyboard: false
[2019-05-16 09:41:02.750] [info] [observer]   is_pointing_device: true
[2019-05-16 09:41:02.750] [info] [observer] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968365) is observed.
[2019-05-16 09:41:02.750] [info] [observer] rescan devices...
[2019-05-16 09:41:02.750] [info] [observer] matching device:
[2019-05-16 09:41:02.750] [info] [observer]   registry_entry_id: 4294968455
[2019-05-16 09:41:02.750] [info] [observer]   manufacturer: Microsoft
[2019-05-16 09:41:02.750] [info] [observer]   product: Microsoft® 2.4GHz Transceiver v9.0
[2019-05-16 09:41:02.750] [info] [observer]   vendor_id: 1118
[2019-05-16 09:41:02.750] [info] [observer]   product_id: 1957
[2019-05-16 09:41:02.750] [info] [observer]   location_id: 0x14500000
[2019-05-16 09:41:02.751] [info] [observer]   is_keyboard: false
[2019-05-16 09:41:02.751] [info] [observer]   is_pointing_device: true
[2019-05-16 09:41:02.751] [info] [observer] rescan devices...
[2019-05-16 09:41:02.752] [info] [observer] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968455) is observed.
[2019-05-16 09:41:02.752] [info] [observer] Apple Internal Keyboard / Trackpad (device_id:4294968215) is observed.
[2019-05-16 09:41:02.761] [info] [observer] Apple Internal Keyboard / Trackpad (device_id:4294968221) is observed.
[2019-05-16 09:41:04.914] [info] [observer] matching device:
[2019-05-16 09:41:04.914] [info] [observer]   registry_entry_id: 4294968820
[2019-05-16 09:41:04.914] [info] [observer]   vendor_id: 1452
[2019-05-16 09:41:04.914] [info] [observer]   product_id: 34304
[2019-05-16 09:41:04.914] [info] [observer]   is_keyboard: true
[2019-05-16 09:41:04.914] [info] [observer]   is_pointing_device: false
[2019-05-16 09:41:04.914] [info] [observer] rescan devices...
[2019-05-16 09:41:04.920] [info] [observer] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is observed.
[2019-05-16 09:42:07.888] [info] [grabber] current_console_user_id: 600708325
[2019-05-16 09:42:07.888] [info] [grabber] receiver is terminated
[2019-05-16 09:42:07.888] [info] [grabber] receiver is initialized
[2019-05-16 09:42:08.124] [error] [observer] grabber_client error: Connection reset by peer
[2019-05-16 09:42:08.124] [info] [observer] grabber_client is closed.
[2019-05-16 09:42:08.434] [info] [observer] grabber_client is connected.
[2019-05-16 09:42:08.434] [info] [observer] rescan devices...
[2019-05-16 09:42:25.835] [info] [console_user_server] version 12.4.0
[2019-05-16 09:42:26.335] [info] [console_user_server] karabiner_grabber_alerts.json is updated.
[2019-05-16 09:42:26.691] [info] [console_user_server] receiver is initialized
[2019-05-16 09:42:26.691] [info] [console_user_server] grabber_client is started.
[2019-05-16 09:42:26.691] [info] [console_user_server] grabber_client is connected.
[2019-05-16 09:42:26.962] [info] [grabber] karabiner_console_user_server is connected.
[2019-05-16 09:42:26.962] [info] [grabber] `system_preferences` is updated.
[2019-05-16 09:42:26.963] [info] [grabber] console_user_server_client is connected. (uid:600708325)
[2019-05-16 09:42:26.963] [info] [grabber] device_grabber is started.
[2019-05-16 09:42:26.980] [info] [grabber] event_tap_monitor initialized
[2019-05-16 09:42:26.980] [info] [grabber] virtual_hid_device_client is started.
[2019-05-16 09:42:26.980] [info] [grabber] Load /Users/q4i2/.config/karabiner/karabiner.json...
[2019-05-16 09:42:26.981] [info] [grabber] core_configuration is updated.
[2019-05-16 09:42:26.981] [info] [grabber] virtual_hid_device_client is opened.
[2019-05-16 09:42:26.982] [info] [grabber] virtual_hid_device_client_ is connected
[2019-05-16 09:42:26.982] [info] [grabber] initialize_virtual_hid_keyboard
[2019-05-16 09:42:26.982] [info] [grabber]   country_code:0
[2019-05-16 09:42:26.983] [info] [grabber] initialize_virtual_hid_keyboard
[2019-05-16 09:42:26.983] [info] [grabber]   country_code:0
[2019-05-16 09:42:26.985] [info] [grabber] mouse_key_xy_scale: 100
[2019-05-16 09:42:27.061] [info] [console_user_server] Load /Users/q4i2/.config/karabiner/karabiner.json...
[2019-05-16 09:42:27.064] [info] [console_user_server] core_configuration is updated.
[2019-05-16 09:42:27.247] [info] [console_user_server] Check for updates...
[2019-05-16 09:42:29.970] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 09:42:29.971] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968455) is ignored.
[2019-05-16 09:42:29.974] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968365) is grabbed.
[2019-05-16 09:42:29.974] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 09:42:29.974] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968455) is ignored.
[2019-05-16 09:42:29.974] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 09:42:29.975] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 09:42:30.055] [info] [observer] matching device:
[2019-05-16 09:42:30.055] [info] [observer]   registry_entry_id: 4294969410
[2019-05-16 09:42:30.055] [info] [observer]   manufacturer: pqrs.org
[2019-05-16 09:42:30.055] [info] [observer]   product: Karabiner VirtualHIDKeyboard
[2019-05-16 09:42:30.055] [info] [observer]   vendor_id: 5824
[2019-05-16 09:42:30.055] [info] [observer]   product_id: 10203
[2019-05-16 09:42:30.055] [info] [observer]   location_id: 0x0
[2019-05-16 09:42:30.055] [info] [observer]   serial_number: pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v061000
[2019-05-16 09:42:30.055] [info] [observer]   is_keyboard: true
[2019-05-16 09:42:30.055] [info] [observer]   is_pointing_device: false
[2019-05-16 09:42:30.055] [info] [observer] rescan devices...
[2019-05-16 09:42:30.060] [info] [observer] Karabiner VirtualHIDKeyboard (device_id:4294969410) is observed.
[2019-05-16 09:45:15.410] [info] [observer] device_id:4294968365 is terminated.
[2019-05-16 09:45:15.410] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968365) is terminated.
[2019-05-16 09:45:15.411] [info] [observer] device_id:4294968455 is terminated.
[2019-05-16 09:45:15.411] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 09:45:15.411] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 09:45:15.412] [info] [observer] rescan devices...
[2019-05-16 09:45:15.412] [info] [observer] rescan devices...
[2019-05-16 09:45:15.412] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968455) is ignored.
[2019-05-16 09:45:15.412] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 09:45:15.412] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294968455) is terminated.
[2019-05-16 09:45:15.413] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 09:45:15.413] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 09:45:15.413] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 09:45:34.521] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970192) is ignored.
[2019-05-16 09:45:34.522] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970189) is grabbed.
[2019-05-16 09:45:34.576] [info] [observer] matching device:
[2019-05-16 09:45:34.576] [info] [observer]   registry_entry_id: 4294970189
[2019-05-16 09:45:34.576] [info] [observer]   manufacturer: Microsoft
[2019-05-16 09:45:34.576] [info] [observer]   product: Microsoft® 2.4GHz Transceiver v9.0
[2019-05-16 09:45:34.576] [info] [observer]   vendor_id: 1118
[2019-05-16 09:45:34.576] [info] [observer]   product_id: 1957
[2019-05-16 09:45:34.576] [info] [observer]   location_id: 0x14500000
[2019-05-16 09:45:34.576] [info] [observer]   is_keyboard: true
[2019-05-16 09:45:34.576] [info] [observer]   is_pointing_device: false
[2019-05-16 09:45:34.577] [info] [observer] rescan devices...
[2019-05-16 09:45:34.577] [info] [observer] matching device:
[2019-05-16 09:45:34.577] [info] [observer]   registry_entry_id: 4294970192
[2019-05-16 09:45:34.577] [info] [observer]   manufacturer: Microsoft
[2019-05-16 09:45:34.577] [info] [observer]   product: Microsoft® 2.4GHz Transceiver v9.0
[2019-05-16 09:45:34.577] [info] [observer]   vendor_id: 1118
[2019-05-16 09:45:34.577] [info] [observer]   product_id: 1957
[2019-05-16 09:45:34.577] [info] [observer]   location_id: 0x14500000
[2019-05-16 09:45:34.577] [info] [observer]   is_keyboard: false
[2019-05-16 09:45:34.577] [info] [observer]   is_pointing_device: true
[2019-05-16 09:45:34.577] [info] [observer] rescan devices...
[2019-05-16 09:45:34.578] [info] [observer] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970192) is observed.
[2019-05-16 09:46:09.713] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970192) is ignored.
[2019-05-16 09:46:09.713] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 09:46:09.713] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 09:46:09.713] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 09:46:09.722] [info] [grabber] Ergonomic Keyboard (device_id:4294970236) is grabbed.
[2019-05-16 09:46:09.779] [info] [observer] matching device:
[2019-05-16 09:46:09.779] [info] [observer]   registry_entry_id: 4294970236
[2019-05-16 09:46:09.780] [info] [observer]   manufacturer: Microsoft
[2019-05-16 09:46:09.780] [info] [observer]   product: Ergonomic Keyboard
[2019-05-16 09:46:09.780] [info] [observer]   vendor_id: 1118
[2019-05-16 09:46:09.780] [info] [observer]   product_id: 2071
[2019-05-16 09:46:09.780] [info] [observer]   location_id: 0x12e70df9
[2019-05-16 09:46:09.780] [info] [observer]   is_keyboard: true
[2019-05-16 09:46:09.780] [info] [observer]   is_pointing_device: false
[2019-05-16 09:46:09.780] [info] [observer] rescan devices...
[2019-05-16 10:37:52.565] [info] [observer] device_id:4294970236 is terminated.
[2019-05-16 10:37:52.565] [info] [grabber] Ergonomic Keyboard (device_id:4294970236) is terminated.
[2019-05-16 10:37:52.566] [info] [observer] rescan devices...
[2019-05-16 10:37:52.567] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970192) is ignored.
[2019-05-16 10:37:52.567] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 10:37:52.567] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 10:37:52.568] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 11:02:47.643] [info] [observer] matching device:
[2019-05-16 11:02:47.643] [info] [observer]   registry_entry_id: 4294972817
[2019-05-16 11:02:47.643] [info] [observer]   manufacturer: Microsoft
[2019-05-16 11:02:47.643] [info] [observer]   product: Ergonomic Keyboard
[2019-05-16 11:02:47.643] [info] [observer]   vendor_id: 1118
[2019-05-16 11:02:47.643] [info] [observer]   product_id: 2071
[2019-05-16 11:02:47.643] [info] [observer]   location_id: 0x12e70df9
[2019-05-16 11:02:47.643] [info] [observer]   is_keyboard: true
[2019-05-16 11:02:47.643] [info] [observer]   is_pointing_device: false
[2019-05-16 11:02:47.643] [info] [observer] rescan devices...
[2019-05-16 11:02:47.648] [info] [grabber] Ergonomic Keyboard (device_id:4294972817) is grabbed.
[2019-05-16 11:02:47.677] [warning] [grabber] Ergonomic Keyboard (device_id:4294972817) is ignored temporarily until {"key_code":"a"} is pressed again.
[2019-05-16 11:02:47.678] [info] [grabber] Ergonomic Keyboard (device_id:4294972817) is ungrabbed.
[2019-05-16 11:02:50.730] [info] [observer] Ergonomic Keyboard (device_id:4294972817) is observed.
[2019-05-16 11:02:52.325] [warning] [grabber] Ergonomic Keyboard (device_id:4294972817) is ignored temporarily until {"key_code":"a"} is pressed again.
[2019-05-16 11:02:53.697] [info] [grabber] Ergonomic Keyboard (device_id:4294972817) is grabbed.
[2019-05-16 11:31:23.816] [info] [observer] device_id:4294972817 is terminated.
[2019-05-16 11:31:23.816] [info] [grabber] Ergonomic Keyboard (device_id:4294972817) is terminated.
[2019-05-16 11:31:23.818] [info] [grabber] Microsoft® 2.4GHz Transceiver v9.0 (device_id:4294970192) is ignored.
[2019-05-16 11:31:23.818] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968221) is ignored.
[2019-05-16 11:31:23.818] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968215) is ignored.
[2019-05-16 11:31:23.818] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:4294968820) is ignored.
[2019-05-16 11:31:23.820] [info] [observer] rescan devices...
[2019-05-16 11:33:34.029] [info] [grabber] Ergonomic Keyboard (device_id:4294973735) is grabbed.
[2019-05-16 11:33:34.053] [info] [observer] matching device:
[2019-05-16 11:33:34.053] [info] [observer]   registry_entry_id: 4294973735
[2019-05-16 11:33:34.053] [info] [observer]   manufacturer: Microsoft
[2019-05-16 11:33:34.053] [info] [observer]   product: Ergonomic Keyboard
[2019-05-16 11:33:34.054] [info] [observer]   vendor_id: 1118
[2019-05-16 11:33:34.054] [info] [observer]   product_id: 2071
[2019-05-16 11:33:34.054] [info] [observer]   location_id: 0x12e70df9
[2019-05-16 11:33:34.054] [info] [observer]   is_keyboard: true
[2019-05-16 11:33:34.054] [info] [observer]   is_pointing_device: false
[2019-05-16 11:33:34.054] [info] [observer] rescan devices...
[2019-05-16 11:33:34.171] [warning] [grabber] Ergonomic Keyboard (device_id:4294973735) is ignored temporarily until {"key_code":"h"} is pressed again.
[2019-05-16 11:33:34.173] [info] [grabber] Ergonomic Keyboard (device_id:4294973735) is ungrabbed.
[2019-05-16 11:33:37.136] [info] [observer] Ergonomic Keyboard (device_id:4294973735) is observed.
[2019-05-16 11:34:18.431] [info] [grabber] Ergonomic Keyboard (device_id:4294973735) is grabbed.
[2019-05-16 11:36:57.517] [info] [grabber] Load /Users/q4i2/.config/karabiner/karabiner.json...
[2019-05-16 11:36:57.518] [info] [console_user_server] Load /Users/q4i2/.config/karabiner/karabiner.json...

```

**Comment by thomasthebaker** [comment]
@nathanjd I've found that v12.2.0 is stable with the Microsoft Surface Ergonomic keyboard although I'm on OSX 10.13 High Sierra.

**Comment by sysdevmike** [comment]
I rolled back to High Sierra + 12.4.0 thinking it was a Mojave issue. Unfortunately not. Installing 12.1.0 instead has fixed the issue for me on High Sierra.

Can anybody confirm that 12.1.0 doesn't have the issue, even on Mojave?

**Comment by tekezo** [comment]
Thanks for all feedbacks!

I succeed to reproduce this issue of v12.4.0! (But the reproducibility is very low on my machine.)
This issue seems to occur if the key is released, and at the exact same moment Karabiner-Elements opens the device.

I fixed the problem at v12.4.2.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by sysdevmike** [comment]
@tekezo Thanks for getting on the problem so quickly. Unfortunately I still get the issue in v12.4.2. I can reproduce the problem consistently by toggling my bluetooth keyboard and entering keys as it starts.

In v12.4.2, I still receive the 'temporarily ignored' dialog.

**Comment by tekezo** [comment]
@sysdevmike

Thank you for feedback!

It's intended behavior that the alert is shown.
The current problem is the alert is not hidden when you press the key again.
Are you not able to hide the alert?
Please show me log messages if the alert is shown persistently.

**Comment by sysdevmike** [comment]
Sorry, I thought the fix was to prevent key-stuck from occurring at all. For whether or not the alert bug is fixed, I'm not too sure, the alert has always properly dismissed itself in my experience.

**Comment by jaredmichaelwilliams** [comment]
Anything about this? Keeps coming up and the karabiner changes no longer work when its being "ignored"

**Comment by tekezo** [comment]
I added a configuration to reduce the delay before open device at v12.4.7. (latest beta version)
Reduce the value may decrease the notification frequency.

Note:
The notification will be shown if you hold keys or buttons down before Karabiner-Elements open the device even with the latest beta.
This behavior is necessary to avoid macOS key stuck issue, thus we cannot remove the notification.

<img width="1000" alt="Screen Shot 2019-06-03 at 11 09 58" src="https://user-images.githubusercontent.com/659178/58771887-8c5c9100-85f1-11e9-9468-d9f1e489a1d3.png">

**Comment by tekezo** [comment]
I've improved the notification behavior to be easy to hide it at v12.4.9. (latest beta version)
(You can hide the notification by another key which can stop key repeating.)

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by ccdredzik** [comment]
Can we just disable it at all? Especially on a locked screen, where it has weird behaviour? i.e.: I can use all keys but enter, so I can type in my password, but not log in, so I have to use builtin keyboard in the end.

**Comment by sysdevmike** [comment]
Thanks, it generally works pretty well, but it looks like keys are still getting stuck (just ignored & dismissed smoothly). I get that it's a mac OS compatibility issue, but does it exist in 11.6? 

Where in 12.5, I can accurately reproduce the keystuck, in 11.6 log just shows that the keyboard isn't grabbed until it's ready. 

![image](https://user-images.githubusercontent.com/11449462/59399021-63948280-8dcd-11e9-860a-c5111366faf4.png)

**Comment by ajhool** [comment]
I upgraded to the beta and things were working for a while, but am now seeing the error again.

**Comment by bengurno** [comment]
I'm getting the error, I have a broken z key that acts as if it is constantly pressed and everytime I use a key on the same row it prangs out and that message appears

**Comment by ajhool** [comment]
@tekezo this issue is still not fixed, would it be possible to revert the code back to the previous working version or to add a "downgrade" option to the misc section of the toolbar that would enable downgrading to previous versions?

**Comment by momomo** [comment]
I am having this same issue, always with the delete key. It just starts deleting my code and i am afraid i won't be able to undo it. Very annoying. Did not occur before. Maybe i should downgrade karabiner. Not sure if it is karabiner though but it appears so.

**Comment by ethanjrt** [comment]
Super frustrating. I downloaded Karabiner because my (Macbook believes that my) shift key is getting stuck in the "pressed" position. Now Karabiner is disabling the keyboard... which leaves my Mac thinking the key is still pressed for whatever reason (not to mention the notification that forever sits on top). I downgraded to 12.3.0 as some have suggested but that seems to have only "half fixed" the problem -- I can now type with lower case letters, but when I perform any actions with the mouse the computer acts as if my shift key is pressed. (So all links are opening in new tabs and I can only properly edit/select text with the keyboard :-p )

Can this be fixed please? Is there a Karabiner alternative?

**Comment by patroza** [comment]
Same problem here. I decided I will just have to learn that my backtick/tilde is next to my left shift, and not left of `1` :D

**Comment by ethanjrt** [comment]
The new update says it fixes this problem (thank you for trying! seriously!), but doesn't, at least not reliably. The "stuck key disabled" message disappeared a few times for me after varying lengths of time, but the third time it popped up it stayed up and the computer thought the shift key was pressed until I restarted. I've re-installed 12.3.0 and it's working fine again.

**Comment by colinjmalone** [comment]
I am experiencing this same issue on Catalina 10.15.4/Karabiner-Elements 12.3 with a Filco Majestouch 2. With Karabiner closed, there is absolutely no issues with the keyboard. Once I have it running with some minimal basic mappings, I am seeing this issue. I will be typing along and all of a sudden it will just repeat out a letter for about 2-3 seconds like I'm holding down the key, e.g. Hello how areeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee . Other times, all key presses stop being recognized for 2-3 seconds. Logs in K-E show nothing - and CPU levels seem to be fine.

**Comment by tchoomak** [comment]
The same iss222222222222222222222222ue on Catalina 10.15.4 with KE 12.9.0 and Logitech K800. Quit KE helps only.

**Comment by AMHUSTLE** [comment]
Same situation here.

Catalina 10.15.5
2020 Macbook Proooooooooooooooooooooooooooooooooooo

Always appreciate dev's efforts on this project.

Would gladly pay for license similar to BetterTouchTool licensing system.

**Comment by Evilweed** [comment]
Same here Karabiner-elements 12.10.0.

**Comment by ZeliTheZealot** [comment]
I have been having this issue as well. Sometimes both my external and apple keyboard would have the same malfunction. 

The `d` key would not respond, despite showing up in Karabiner-EventViewer. Also, every keystroke would have the flag `right_shift`. Confusingly, typing normally does not result in all-caps. 

I would donate if this gets fixed. 

catalina 10.15.5
biner 12.10.0

**Comment by babygau** [comment]
try the [beta](https://karabiner-elements.pqrs.org/docs/macos-big-sur/) build to see if it fix ur issue.

**Comment by ylluminarious** [comment]
@ZeliTheZealot I'm having a similar issue, especially regarding the `d` key. I've been dealing with it for over a year now and I have no clue how to fix it. It seems to just happen intermittently, even though it's definitely not a hardware issue, as it's showing up in the EventViewer for me as well.

**Comment by momomo** [comment]
left_command gets stuck in finder.... does not work ... 


Simple example: 
```


 {
        "conditions": [
            {
                "bundle_identifiers": [
                    "^com.apple.finder"
                ],
                "type": "frontmost_application_if"
            }
        ],
        "from": {
            "key_code": "t",
            "modifiers": {
                "mandatory": [
                    "left_command"
                ]
            }
        },
        "to": [
            {
                "key_code": "c",
                "modifiers": [
                    "left_command"
                ]
            },
            
            {
                "key_code": "escape"
            },
            
            {
                "key_code": "n",
                "modifiers": [
                    "right_command"
                ]
            },

            {
                "key_code": "return_or_enter"
            }
        ],
        
        "type": "basic"
    }
```

**Comment by MuhammedZakir** [comment]
@momomo: In `to.modifiers`, replacing `left_command` with `right_command` might solve it.

**Comment by momomo** [comment]
@MuhammedZakir It does not. Already tried it. Please fix this as this is not very stable. Right now I am not sure what happens, but it ends up in a state that destroys finder at least. It is not a finder issue though.

**Comment by alextheyoung** [comment]
I am really grateful for this application but I would appreciate it infinitely if you could add a toggle button to disable this completely. My mac has a hardware problem with its keyboard so that every time I press E, D or C my 3 key is also pressed. I've disabled the 3 key completely and use F3 for it, but every time I press the problem keys in a combination, like command+c, or when I'm typing quick so that I am pressing a key before releasing another, the protection mechanism gets triggered and I end up with 3's.

**Comment by yk4r2** [comment]
Returned back after updating to 15.3.0 :(

**Comment by Taka986** [comment]
So all we have to do is uninstall

**Comment by giacomorebonato** [comment]
This is still a pain... Any new suggestions?

**Comment by ApolloTang** [comment]
uninstalled
