### ISSUE TITLE
"Force Quit…" shortcut doesn't work

### ISSUE THREAD

**Issue by 343max** [tekezo/Karabiner-Elements#236]
Command-Option-Escape doesn't open the "Force Quit" dialog when Karabiner Elements is installed. Verified on Sierra and El Capitan.

**Comment by saagarjha** [comment]
+1 Was having this issue this morning and was going to file an bug…turns out this is related to #89.

**Comment by tekezo** [comment]
I've fixed this issue in v0.90.47.

Please upgrade to the latest version from "Misc > Check for updates" or
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by saagarjha** [comment]
I'm still having issues with the the Alt key (for example, using Alt-drag to make a rectangular selection or Alt-click moving the cursor in iTerm).
