### ISSUE TITLE
Keyboard gone mad when Karabiner-Elements is quit or uninstalled

### ISSUE THREAD

**Issue by DCCXI** [tekezo/Karabiner-Elements#248]
The "g" on the internal keyboard not responding. The "a" on the bluetooth keyboard (Filco MINILA) is not responding and "h" became "i" when pressed.

**Comment by BrianGilbert** [comment]
Did you disable it before you uninstalled?

**Comment by dkleehammer** [comment]
:+1:

Also having this issue.

**Comment by nikitavoloboev** [comment]
I have something similar in that my keyboard goes mad and starts sending wrong key codes for each key pressed. Some keys even stop working. I am using Karabiner on El Captain though.

Really frustrating.

**Comment by BrianGilbert** [comment]
I have dialog popping up to search for bluetooth keyboards which I think must be related to this..

**Comment by barttenbrinke** [comment]
I have the exact same thing. Stopping Karabiner Elements disables my keyboard completely. Restarting it restores all functionality.

**Comment by tekezo** [comment]
I believe this issue has been fixed the latest version.

**Comment by kitora** [comment]
No I still have problem unfortunately...
After updatin to 0.9.63, I uninstalled Karabiner-Elements.
But "g" didn't come back. 

Karabiner-EventViewer does not reconize "g" key operations.

**Comment by TGlas** [comment]
I have the same issue as barttenbrinke: after I quit karabiner my keyboard is gone completely. The only option to recover is to restart karabiner elements with mouse only - quite annoyong for a keyboard centric user. I am using version 11.0.0 on MacOS Sierra 10.12.6, Macbook Pro mid-2012, and my only (physical) keyboard is the built-in one.
