### ISSUE TITLE
Internal MacBook keyboard does not work after quitting K-E

### ISSUE THREAD

**Issue by mafredri** [tekezo/Karabiner-Elements#268]
If I quit Karabiner-Elements I am left without a keyboard (assuming no external keyboard is connected). The internal MacBook (Pro) keyboard does not respond to any keypresses and the system no longer sees any keyboard present.

Soon after, the Bluetooth Setup Assistant pops up informing me that there is no keyboard present:

<img src="https://www.dropbox.com/s/fi8pkchfgzjlpi9/Screenshot%202016-10-05%2009.56.07.png?dl=1" height=300>

**Comment by Schemetrical** [comment]
Same, except bluetooth setup pops up every time I unlock my computer as well.

**Comment by codyrobbins** [comment]
I ran into the same problem—it left me unable to log back in after locking my screen.

**Comment by dlehman** [comment]
I think this issue is fixed in the latest update (I'm running 0.90.48).

In previous versions of KE, whenever I woke my MacBook Pro from sleep, the Bluetooth Keyboard Setup assistant would pop-up, and some keys wouldn't work. If I would kill KE, no keys would work, but if I would restart it, everything would work fine. So I would:

- open Karabiner-Elements using LaunchBar
- kill KE (keyboard stops working)
- use mouse to click LaunchBar icon on dock, which would show Karabiner-Elements as last item opened, so I could click it to restart

**Comment by codyrobbins** [comment]
I’m running 0.90.48 and still having the Bluetooth Setup Assistant popping up intermittently, although the keyboard hasn’t fully died on me again yet.

**Comment by mafredri** [comment]
Definitely not fixed, my keyboard remains completely dead (no keys work). Running 0.90.48 as well.

**Comment by SConaway** [comment]
works on 0.90.52 with mid-'14 mbp 15

**Comment by passabilities** [comment]
I'm running 0.90.52 and keyboard is still dead after quitting.

**Comment by codyrobbins** [comment]
It’s still happening for me on 0.90.52. Every time I leave my computer at the login window for more than a few minutes the keyboard completely dies making it impossible to log back in without power cycling the computer.

**Comment by tekezo** [comment]
I believe this issue has been fixed in the latest version.

**Comment by Schemetrical** [comment]
I have the same problem with Bluetooth Setup Assistant popping up with latest version, but the keyboard isn't disabled this time.

**Comment by codyrobbins** [comment]
@tekezo このフィックスを本当にありがとうございます。しかも、高山さん、カラビナーは、お疲れ様です！

The problem of the keyboard dying on the login window is indeed now fixed for me too.

**Comment by codyrobbins** [comment]
Unfortunately I spoke to soon—this problem has continued to happen for me, albeit intermittently. I’m on version 0.90.64 and it just happened again almost immediately when using the fast user switching menu to lock my computer without putting it to sleep. However, it’s not happening every time.

**Comment by codyrobbins** [comment]
As an update, this problem still seems to be occurring and I think this issue needs to be reopened. If I log out of my user account entirely, as of 0.90.77 the keyboard still dies and there’s nothing I can do to get back into the computer without turning it off and turning it back on.

**Comment by codyrobbins** [comment]
Perhaps related or a duplicate of #466 or #534.

**Comment by F1LT3R** [comment]
I'm running 0.90.92 and I have no keyboard input after locking the screen.
