### ISSUE TITLE
Pressing keys causes beeping, even outside Karabiner Elements

### ISSUE THREAD

**Issue by asmeurer** [tekezo/Karabiner-Elements#27]
I'm using Karabiner Elements 0.90.27. Here is my karabiner.json

``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "fn": "left_control",
                "f12": "delete_forward"
            }
        }
    ]
}
```

I can reproduce the issue like this:
- Open Karabiner Elements window and type some letters (like `asdf`). This will cause it to start beeping for each letter. 
- Type some command keys, like `Ctrl`, `Option`, `Command`. These will also beep. 
- Now use the mouse to switch to another application, say Chrome. 
- Type the command keys, `Ctrl`, `Option`, `Command`. These will continue to beep, although they seem otherwise functional. 
- As soon as you type a letter in the other application, the beeping goes away. 

The beeping in the other application is the bug here, but personally, I would rather not have any beeping even in Karabiner Elements, as its annoying, and seems unnecessary.

**Comment by asmeurer** [comment]
Oh and I'm on Sierra 10.12 Beta (16A313a)

**Comment by asmeurer** [comment]
So this issue actually triggers more often than just by doing that.  Sometimes, after using `fn + arrow` (i.e., `control + arrow`) to switch spaces, it happens, even when the Karabner Elements window is not open. It doesn't happen every time, and I'm unsure how to reproduce it. The above steps reproduce the issue every time.

**Comment by talha131** [comment]
@asmeurer You should try the update 0.90.29. 

> Open Karabiner Elements window and type some letters (like asdf). This will cause it to start beeping for each letter. 

Also this is true for all windows. Say you quit Karabiner-Elements, open "About This Mac". Press character keys, you will hear the warning bell.

**Comment by matthewdias** [comment]
I believe this is fixed on latest release.

**Comment by RianGray** [comment]
I can confirm the issue is still happening on the latest release, v0.9.46.
