### ISSUE TITLE
F-keys don't work when Karabiner-Elements is running on Mac Sierra

### ISSUE THREAD

**Issue by assembler** [tekezo/Karabiner-Elements#274]
Elements did a good job of remapping the Caps key to Esc. However, when it is running, I'm unable to F keys on my Kinesis Freestyle2 Blue Mac keyboard. It is the same regardless of my "Use all F1, F2, etc. keys as standard function keys" in osx keyboard settings.

Here is my karabiner.json file: 

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "escape"
            }
        }
    ]
}
```

**Comment by dgow** [comment]
same here! any ideas how to fix it?

**Comment by ZhangBanger** [comment]
Opposite problem - I can't use the F keys as regular F keys.

**Comment by petrsel** [comment]
Maybe try to add the f-keys specification in json file as follows:

	{
	  "profiles" : [
		{
		  "fn_function_keys" : {
			"f1" : "vk_consumer_brightness_down",
			"f2" : "vk_consumer_brightness_up",
			"f3" : "vk_mission_control",
			"f4" : "vk_launchpad",
			"f5" : "vk_consumer_illumination_down",
			"f6" : "vk_consumer_illumination_up",
			"f7" : "vk_consumer_previous",
			"f8" : "vk_consumer_play",
			"f9" : "vk_consumer_next",
			"f10" : "mute",
			"f11" : "volume_down",
			"f12" : "volume_up"
		  },
		  "name" : "Default profile",
		  "selected" : true,
		  "simple_modifications" : {

		  }
		}
	  ]
	}

**Comment by ZhangBanger** [comment]
Actually trying to do exact opposite. How would I get the F6 key working as F6?

**Comment by petrsel** [comment]
In this case try: 
`"f6" : "f6"`

**Comment by assembler** [comment]
@petrsel this didn't work for me. on my keyboard in order to get to F keys, i have to press Fn+F. When doing so, i can do simple_modification of F1 to letter 'a' and when i press Fn+F1 it types 'a'. 

However, I can't get the volume keys to work (those should work without pressing the Fn key). 

It worked with Seil before I upgraded to Sierra out of the box.

**Comment by assembler** [comment]
In other words fn_function_keys.f1 collides with simple_modifications.f1 - both point to same "Fn+F1" key.

**Comment by petrsel** [comment]
@assembler And what settings are you using for "Keyboard - Use F-keys as standard keys" in System Preferences? I have this disabled, and Karabiner is handling them. I would also remove the code from simple_modifications and use just fn_function_keys.

**Comment by petrsel** [comment]
I should've also mention I am using internal keyboard of my MB Pro.

**Comment by assembler** [comment]
I have that system preference unchecked just like you. I could remove code from simple_modifications, and only use fn_function_keys but then I wouldn't have what i need: F4 maps to F4 and Fn+F4 maps to vk_launchpad for example. 

Come to think of it it is the exact problem that @ZhangBanger is having - i can map Fn+F keys, but I can't map the F keys without Fn.

Btw, it works fine on my internal MB Pro keyboard, it doesn't work with the bluetooth keyboard that I'm using.

**Comment by assembler** [comment]
This is strange.. I've opened up visual keyboard on mac, and when i press F4 (without any karabiner modifications to it) it highlights the F12 key. Then if I map F12 key to F4 (via simple modifications) I finally get F4 key to work as F4. This works only for F4 sadly :(

**Comment by ZhangBanger** [comment]
Is there a "don't remap apple/internal" option?

The whole point of this  (I thought) was to remap other keyboards like Windows/Microsoft. That's where my F keys don't work. Remapping F6->F6 does nothing useful.

**Comment by jpdborgna** [comment]
I'm having the same issue. I need the play/pause(F8) to still be play/pause so I can map caps_lock to F8. 
I tried by removing the section from the json file and maping capslock to f8 but now both keys (F8 without Fn and capslock) are play/pause. 
So, to be clear, I need to map capslock -> F8 (key code 100, as if pressing Fn+play/pause)
And leave alone the play/pause as in pressing the key without Fn

**Comment by KTamas** [comment]
same issue, it drives me crazy :\

**Comment by toyg** [comment]
Apparently [this email](https://groups.google.com/d/msg/osx-karabiner/MxJO74XYkrE/AFB6gat8HgAJ) includes a working private.xml meant for the original Karabiner - how would we go about reimplementing that for K-Elements?

**Comment by szkrd** [comment]
Why can't this "feature" be turned off? With the newest update I got a Function keys tab, but no matter what I set there, it's wonky :(

**Comment by ZhangBanger** [comment]
This has been fixed - thank you!

**Comment by incandescentman** [comment]
What fixed this problem for me is going to Devices > Modify events from this device, and disabling a extra keyboard that was listed there and checked but that is not the one I'm using.

**Comment by kornerr** [comment]
Actually, it's not been fixed. I've just upgraded from El Capitan to Sierra, and all F keys act as Fn + F keys.

**Comment by kornerr** [comment]
![screen shot 2017-07-13 at 13 18 27](https://user-images.githubusercontent.com/4783608/28153085-cfb5dfcc-67cd-11e7-86e0-ff8dbeb22aef.png)
Turns out, all I had to do is check 'Use all F1, F2, etc. keys as standard function keys'.
Now F keys work as F keys!

**Comment by juanibiapina** [comment]
And in the current version of karabiner-elements, also make sure to delete the fn keys specification from the json. This was needed at some point but now it isn't anymore. When you delete and check the checkbox above, they behave as the default.

**Comment by budowski** [comment]
Not really fixed:
1. Sierra 10.12.6
2. Karabiner-Elements 0.91.16
3. "Use all F1, F2, ... as standard functions keys" option - both check on and off (didn't help).
3. Deleted "fn" settings from JSON file:
```json
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.to_if_alone_timeout_milliseconds": 1000
                },
                "rules": []
            },
            "devices": [],
            "name": "Default profile",
            "selected": true,
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "caps_lock"
                    },
                    "to": {
                        "key_code": "escape"
                    }
                },
                {
                    "from": {
                        "key_code": "right_option"
                    },
                    "to": {
                        "key_code": "left_control"
                    }
                }
            ],
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
```

**Comment by nicmar** [comment]
What worked for me was when I removed all "fn_function_keys" { ... } sections in the karabiner.json. The issue i was having was that the touchbar didn't show when I pressed the fn-key. I also have an external keyboard that F-keys didn't work, but I can't test it at the moment, hopefully this solved it!

**Comment by budowski** [comment]
I tried removing that section, as you can see my json file above, it didn't work, I'm afraid...
(I'm not using an external keyboard)

**Comment by mts749** [comment]
Same here:
- MacBook Pro (15-inch, 2017)
- Sierra 10.12.6
- Karabiner-Elements 11.1.0
- "Use all F1, F2, ... as standard functions keys" option - both check on and off (didn't help).
- Deleted "fn" settings from JSON file

**Comment by Jeetah** [comment]
Seems like Karabiner is still not usable for any developer on any MAcbook with Touchbar since there  is no solution so far for this issue. Would like to be corrected of wrong :-)

**Comment by PeiyiMusik** [comment]
actually I'm using this, since I only need the fn keys for certain professional programmes:
<img width="339" alt="2018-01-11 11 40 14" src="https://user-images.githubusercontent.com/14304131/34821625-ae371e66-f6c4-11e7-9496-cbd1fcdc22fd.png">
it was then been disabled.
Is there an option to completely disable the function keys feature in Karabiner and let other programme take control?

**Comment by Jeetah** [comment]
Seems like this problem is solved - either by Karabiner update or by one of macOS...

**Comment by acjay** [comment]
I'm still experiencing this issue. For the life of me, I can't get my F-keys to act like regular F-keys on my Kinesis Freestyle2 Blue. I would think there would be a preset that does this (a Complex Modification maybe?). This is really frustrating.

I've tried to manually do 

```
                    "simple_modifications": [
                        {
                            "from": {
                                "consumer_key_code": "display_brightness_decrement"
                            },
                            "to": {
                                "key_code": "f1"
                            }
                        },
                        {
                            "from": {
                                "consumer_key_code": "display_brightness_increment"
                            },
                            "to": {
                                "key_code": "f2"
                            }
                        },
                        {   
                            "from": {
                                "consumer_key_code": "play_or_pause"
                            },
                            "to": {
                                "key_code": "f6"
                            }
                        },
                        {
                            "from": {
                                "consumer_key_code": "mute"
                            },
                            "to": {
                                "key_code": "f8"
                            }
                        }
                  ]
```

It seems to work alright for `f6` and `f8`, but not for remapping brightness to `f1` and `f2`. It seems like something might be wrong with my syntax, because I'm seeing this:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/1256382/36127770-08f9ff68-102d-11e8-9052-af4eb630f54b.png">

**Comment by Aerlinger** [comment]
Same here, still having this issue and it's really frustrating. Would like to use karabiner-elements but don't see being able to forgo using function keys.

**Comment by johnculviner** [comment]
After much trial and tribulation I think I got this working as I wanted reliably now on a Macbook with a 
blasted Touchbar (F keys are available and working in my programming applications!) Here is my setup and I hope this helps someone:

![image](https://user-images.githubusercontent.com/1644353/40489441-b935966c-5f2e-11e8-800a-6daf743ed207.png)

![image](https://user-images.githubusercontent.com/1644353/40489462-c976a4a8-5f2e-11e8-94e4-000c7f684c0d.png)

![image](https://user-images.githubusercontent.com/1644353/40489540-f8fef9d2-5f2e-11e8-8b93-4fad2c7257eb.png)

**Comment by wheleph** [comment]
Unfortunately the steps described by @johnculviner above do not for me on High Sierra with Kinesis Freestyle2 Blue.
@acjay @assembler I see that you have the same keyboard model. Were you enable to solve the issue?

**Comment by acjay** [comment]
@wheleph Nope, unfortunately.

**Comment by wheleph** [comment]
@assembler @acjay 

Apparently Kinesis introduced the regression in their Kinesis Freestyle2 **Blue** for Mac. Here's the quote for the user guide: 

> To use the traditional function keys (blue legends on the keyboard, listed in parentheses below), **hold down** the fn key.

While for the wired version the behavior is different:

> To use the traditional function keys (blue legends on the keyboard, listed in parentheses below), **toggle on** the fn action.

I got in touch with Kinesis support and they told me that this behavior will be changed back (to toggle) in the upcoming revisions of "Blue" keyboard.

Unfortunately it doesn't help the owners for the current revision...

**Comment by mwhitis** [comment]
I know this is an old, closed issue, but it was the first google result for me when I searched this today.  Just wanted to post my 2 cents on the off chance that it helps someone in the future.  For me, the fix was that my keyboard (logitech 850) has a management app that has it's own checkbox for the "use f1-f12 as standard function keys" setting.  In order to make it work, it has to be checked in all 3 places.  I wouldn't have even thought to look there until @wheleph started talking about his Kinesis, so appreciate the assist. :)

**Comment by Ghedeon** [comment]
> After much trial and tribulation I got this working as I wanted reliably now on a MacBook with a
> blasted Touchbar. The function keys are available and working in my programming applications where I want them! Here is pretty much the only setup I could get to work. Hope this helps someone:
> 
> ![image](https://user-images.githubusercontent.com/1644353/40489441-b935966c-5f2e-11e8-800a-6daf743ed207.png)
> 
> ![image](https://user-images.githubusercontent.com/1644353/40489462-c976a4a8-5f2e-11e8-94e4-000c7f684c0d.png)
> 
> ![image](https://user-images.githubusercontent.com/1644353/40489613-1927d30a-5f2f-11e8-9afd-c7805292ae3d.png)
> 
> ![image](https://user-images.githubusercontent.com/1644353/40489699-4ecf285a-5f2f-11e8-83e1-026f9a3184c4.png)

I don't know why it's marked as closed but this guy is a hero. When I already decided that it's a snowball's chance in hell to make it work, the weird combination of unrelated checkboxes above did the miracle.

Mojave 10.14.6
Karabiner-Elements 12.9.0

**Comment by avshyz** [comment]
Tried following @johnculviner 's steps, to no avail.
Using the builtin keyboard, catalina 10.15.4
