### ISSUE TITLE
Bluetooth Wireless Mouse doesn't work

### ISSUE THREAD

**Issue by leohsu91** [tekezo/Karabiner-Elements#39]
Hello.
I used the latest Karabiner-Elements v0.90.36. My Mac's version is 10.12 Sierra. I editor the **karabiner.json** to switch Option Key to Command Key. It works on my keyboard very well(also Buletooth wireless keyboard).
But on the while my bluetooth wireless mouse doesn't work(Logitech MX Master).
When i quit Karabiner-Elements, my mouse can work again.

Thank you for provider this excellent software. Can you tell me how to fix it?
Thanks very much!

**Comment by leohsu91** [comment]
this is config file
```
{
    "profiles": [
        {
            "name": "VB87M",
            "selected": true,
            "simple_modifications": {
                "left_option": "left_command",
              	"right_option":"right_command",
              	"left_command": "left_option",
              	"right_command":"right_option"
            }
        }
    ]
}
```

**Comment by aynroot** [comment]
I have the same problem. After a couple of seconds since I open Karabiner-Elements my Logitech mouse (connected with Logitech bluetooth dongle) stops working.
It is still "connected" in the Logitech options menu, but unresponsive.
As soon as I close the software everything is fine again.

**Comment by torsteins** [comment]
I have the same problem, my USB mouse (Contour RollerMouse Pro2) stops working when Karabiner-EIements is open, but starts working again immediately when I quit. Even if config file is empty.

**Comment by shaungrady** [comment]
I also have an issue with the mouse. I have a Logitech G602 that I use with **SteerMouse**. If Karabiner-Elements runs before SteerMouse, it breaks SteerMouse. I have to quit Karabiner-Elements, re-run SteerMouse, then start KE again for things to work.

Would love a way to disable mouse functionality in KE entirely.

**Comment by tekezo** [comment]
Thank you for feedback!
I believe this issue has been fixed at v0.90.33.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by Ivan0xFF** [comment]
I'm using v0.90.36 on macOS Sierra and this issue is still occurring with my Bluetooth Mouse.

**Comment by torsteins** [comment]
Thank you very much for being attentive of this. The issue is still present on v0.90.36 for me as well.

**Comment by leohsu91** [comment]
Thank you so much for your reply to me.The issue is still present on v0.90.36 for me  too.

**Comment by songsanli** [comment]
Same issue as above. I'm using MX Master mouse. From shaungrady's response, I guess start of Karabiner-Elements will break running mouse drive (in my case, KE breaks behavior of Logitech Options, the drive app of MX Master mouse).

**Comment by ghreat** [comment]
I have the USB mouse **Mionix Naos 5000**. I can confirm that this issue still exists with *v0.90.37*.

**Comment by sumsethan** [comment]
same issue with Microsoft Sculpt Comfort Mouse at v0.90.38.And hope for a eject key modification

**Comment by shibei00** [comment]
I have the same issue with Logitech M558 wireless bluetooth mouse and v0.90.40. My system is macOS.

**Comment by SpaceK33z** [comment]
As said in #84, it looks like this has been fixed in version 0.90.41, with commit 2a769ddda075b50cd742ca9593cafd6f3fcbf18d. I also had this problem before (MX Master), and it works now :).

**Comment by ghreat** [comment]
My USB mouse **Mionix Naos 5000** is working again after updating to *v0.90.42*, awesome. Many thanks!

**Comment by leohsu91** [comment]
the lastet version 0.90.42 had solved this problem. waiting for the GUI setting version. Thanks a lot.

**Comment by tekezo** [comment]
I've changed the approach in v0.90.45.
Please confirm this issue also fixed in v0.90.45.

**Comment by songsanli** [comment]
v0.90.45 enables the movement of my **MX Master** (bluetooth connection). However, buttons on my mouse don't work anymore. Logitech uses Logitech Options to customize buttons of theirs mouse. And I guess v0.90.45 has conflict with it.

Also, Karabiner-Elements will auto change the position of *command* key and *option* key 😞. I'm using Realforce 87USW keyboard.

**Comment by leohsu91** [comment]
the same situation with upstairs.  (MX Master can move, but the customized function is disabled)
And Since V0.90.42 version I found another issue.
The original key map of my keyboard is not working. instead of it is MacBook's key map.
example：my keyboard F9 is "Volume up"，but use Karabiner-Elements, it will change to "Next Song" function key. Karabiner-Elements sets my keyboard to the same key  map as the MacBook by default.
![Uploading 944B3A1
![944b3a16-766d-4343-84af-0437aa51abe3](https://cloud.githubusercontent.com/assets/8965956/18943473/67d08cf2-8652-11e6-9cba-bfaa7909c9a1.png)
6-766D-4343-84AF-0437AA51ABE3.png…]()

**Comment by leohsu91** [comment]
楼上帅气的小伙子。你的QQ/微信号是多少。- -。

**Comment by torsteins** [comment]
This issue is still present in v0.09.46.

**Comment by nickmcummins** [comment]
Hey, so I remember having this issue originally. When I updated to v0.90.45, the issue was fixed. 

It seems like with the latest version (v0.90.46 -- and I've "Checked for Updates") this issue is happening again. I have had to uninstall the app for the meantime.

**Comment by SConaway** [comment]
works in 0.90.48

**Comment by nickmcummins** [comment]
It works on 0.90.48 now for me too but I had to disable and re-enable bluetooth. So this may have been the case in 0.90.46 as well.

**Comment by RianGray** [comment]
Can anyone elaborate how did you manage to make a bluetooth mouse to work? I'm the guy who posted #218, but it still doesn't work for me with karabiner elements v0.90.48 and logitech v.6.30.48.

**Comment by SConaway** [comment]
All I did was switch the mouse off and then back on and it worked.

**Comment by RianGray** [comment]
Well bummer. I can confirm it still doesn't work with Logitech MX Master. Just to clarify, its the additional buttons and features that stop working. Moving pointer and left clicking still work. Logitech Options suddenly stop picking the mouse up once Karabiner is running. It's the same behavior as it was described in #218.

**Comment by peppeuz** [comment]
Same problem on Karabiner-Elements 0.90.48.

I use a Microsoft Sculpt Comfort mouse but it completely stops working when I open Karabiner-Elements.

**Comment by rnbarg** [comment]
Same problem - the workaround is to turn Bluetooth on and off and the mouse will work fine.  In order to do this you have to have a 2nd mouse using USB also plugged in. Once you cycle the BT on and off the mouse works fine.

**Comment by RianGray** [comment]
v0.90.50 is now making mouse completely unresponsive, from moving the pointers to basic left/right clicking. The workaround(turning on/off bluetooth) didn't work for me, but connecting via USB dongle still works. For those who don't have emergency wired mouse, just make Siri do it for you. Siri can now turn on/off bluetooth as well.

**Comment by SConaway** [comment]
on 0.90.52 mouse works after restart of mouse.

**Comment by rnbarg** [comment]
on 0.90.52 mouse works after restart of mouse. TRUE and a welcome improvement
However, The default back and forward buttons on the the Logitech MX Master and Logitech VX Revolution continue to be rendered useless when  Karabiner Elements is active. This is a deal braker for me. 
![2016-10-17_09-17-38ddddddddddd](https://cloud.githubusercontent.com/assets/10092862/19445798/aa8f0c02-944a-11e6-9023-675562150d1b.jpg)

**Comment by rnbarg** [comment]
All that said, this is an invaluable program which I sorely miss having on Sierra and I thank Tezeko for continuting to develop it so it works w/Sierra.

**Comment by CJSF2323** [comment]
Seeing erratic behavior with my Logitech M705, a USB mouse using Logitech's Unifying Software. It seems like ~10% of the time clicks are delayed or held for a few seconds. I've unplugged the receiver and removed the batteries a couple times, to no avail. Using 0.90.53 with Sierra.

**Comment by peppeuz** [comment]
Switching BT off and on again actually works as workaraund.
Thanks @rnbarg

**Comment by bezhermoso** [comment]
Chiming in to report that I'm still having the same problem with the most recent release `0.90.55` on MacOS Sierra. I'm also using a Logitech MX Master. 

Restarting the mouse nor restarting BetterTouchTool does not solve it for me, unfortunately.

**Comment by SConaway** [comment]
no problem on 0.90.55

**Comment by torsteins** [comment]
As workaround for version 0.90.55, it works for me to unplug and replug the USB keyboard.

**Comment by tekezo** [comment]
Thank you for feedbacks!
I added Devices tab in Karabiner-Elements Preferences which allows you to ignore specific devices and ignore the keyboard-and-mouse combined device in default.
Please upgrade to the latest version and check the Devices tab in Preferences.

**Comment by RianGray** [comment]
@tekezo Thank you so much! Devices tab fixed the issue for me (logitech MX master).

For those who are wondering which one must be disabled from the menu, it's shown as ((null)). Check for log if you need to check vendor ID and product ID. Type is shown as keyboard, pointing device.

**Comment by ivan-m** [comment]
With these changes, does it mean that it isn't possible to re-bind the extra keys on my mouse (which uses the same transceiver as the keyboard) with karabiner-elements?

**Comment by marchaase** [comment]
I have a Microsoft Comfort Sculpt Mouse.  Whenever Karabiner-Elements v11.1.0 starts the moues stops working (cursor can't move, clicking does nothing).  If I turn the moues off and then on again, functionality works fine again and the button remap I have for the mouse configured works.

**Comment by xbjconan** [comment]
Hi @marchaase 
Do your json code have a modified function on the tilt and click of the scrollwheel on MS comfort sculpt mouse? If possible could you please share your json code with me/us?

Thank you

**Comment by marchaase** [comment]
`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": false,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.to_if_alone_timeout_milliseconds": 1000
                },
                "rules": []
            },
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": true,
                        "product_id": 1954,
                        "vendor_id": 1118
                    },
                    "ignore": false,
                    "simple_modifications": [
                        {
                            "from": {
                                "key_code": "left_command"
                            },
                            "to": {
                                "key_code": "mission_control"
                            }
                        }
                    ]
                },
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 49948,
                        "vendor_id": 1133
                    },
                    "ignore": true,
                    "simple_modifications": []
                },
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 610,
                        "vendor_id": 1452
                    },
                    "ignore": true,
                    "simple_modifications": []
                }
            ],
            "fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "mission_control"
                    }
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": {
                        "key_code": "launchpad"
                    }
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": {
                        "key_code": "illumination_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": {
                        "key_code": "illumination_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": {
                        "consumer_key_code": "rewind"
                    }
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": {
                        "consumer_key_code": "play_or_pause"
                    }
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": {
                        "consumer_key_code": "fastforward"
                    }
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": {
                        "consumer_key_code": "mute"
                    }
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": {
                        "consumer_key_code": "volume_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": {
                        "consumer_key_code": "volume_increment"
                    }
                }
            ],
            "name": "Default profile",
            "selected": true,
            "simple_modifications": [],
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
`

**Comment by marchaase** [comment]
hrm... I had Karabiner-Elements set to start at login, and that may have been the problem.  It seems when the GUI portion of the app first opens up is when the mouse stops functioning.  The key/mouse remap seems to still work as I am assuming the application is running in the background.
