### ISSUE TITLE
Discord Keybind Issue

### ISSUE THREAD

**Issue by MailBackwardsGH** [tekezo/Karabiner-Elements#447]
I frequent Discord and it seems that once using Karabiner Elements, I am unable to set keybinds for anything using my keyboard. Keybinds worked fine before macOS and now it's impossible to set any.

**Comment by pangeacake** [comment]
I am experiencing this issue as well.

**Comment by pangeacake** [comment]
Appears to be resolved?

**Comment by pangeacake** [comment]
Nevermind, seems to be a problem most of the time still.

**Comment by pangeacake** [comment]
May be because discord does not detect the virtual device Karabiner uses?

**Comment by pangeacake** [comment]
Appears to work fine after computer is put to sleep and then turned on again.. still a bug though.

**Comment by underscorephil** [comment]
I am having the same issue. Have found no workaround other than quitting Karabiner Elements

**Comment by axsuul** [comment]
Also experiencing this issue as well

**Comment by beaushinkle** [comment]
Me too!

**Comment by kimaero** [comment]
+1

**Comment by MichaelDays** [comment]
Experiencing this issue with 0.91.13 and Discord 0.0.248 on Sierra 10.12.6

Any keyboard that is enabled in K-E Preferences->Modify events from this device cannot record or trigger any Discord key shortcuts in User Settings->Voice->PTT->Shortcut->Edit Keybind or Keybinds->Add a Keybind->Record Keybind.

**Comment by eddiewang** [comment]
+1

**Comment by da7id** [comment]
I'm also having this issue. I also noticed that the emulation program OpenEmu seems to have the same problem. I'm guessing that both applications are not great at receiving virtual keyboard input or something along those lines. I plan to submit bug reports to both of those development teams as well.

**Comment by MaiaVictor** [comment]
Same problem here.

**Comment by NinoScript** [comment]
I just wanted to say that there's a "+1 reaction" 👍 button you can press to avoid notifying everyone. Always avoid comments like "me too", "+1", "same here".

**Comment by arieh** [comment]
any updates on this?

**Comment by youno99** [comment]
I had the same problem and I found a solution!! (perhaps only for mac user)

<< **SOLUTION** >> check the app store for "Push Mic Control" (it's not free / 2,29 EUR)

With this app I can control the microphone of the mac generally! Teamspeak 3 and discord are still unable to set keybinds in combination with karabiner-elements, so I have to use "continuous transmission" ore something like that. But with "Push Mic Control" I have now some options to control the microphone: push to talk, push to mute, always listening, always muted, toggle mode.
You can use these keys: left shift, right shift, left option, right option, left cmd, right cmd, control, fn - or a combination of max. 3 of these keys.

The app needs OS X 10.10 or higher.
(There are some other apps. First I tried the app "PTT", but unfortunately it doesn't work for me.)

**Comment by dannyperson** [comment]
@youno99 nice workaround

we are all mac users, since this is a mac program :)

**Comment by youno99** [comment]
Yes, sorry... I never used a PC and I didn't know if some PC user have the same problem - maybe with other applications. This workaround could help them, too. Of course with different apps... :)

**Comment by ypresto** [comment]
Finally I found this issue is happen only when Karabiner is enabled for target keyboard device.
Interestingly, keybindings settings screen of Discord also does not react to any key input, not only keybindings it self.

**Comment by ypresto** [comment]
Discord official twitter did not reply to my question below.
https://twitter.com/yuya_presto/status/943373874749566977

**Comment by vvsor** [comment]
The issue is still occurring

**Comment by jacortinas** [comment]
I ended up here after buying a vortex race 3 and using KE to help with making it mac compatible. I run into the same issue with discord not being able to get any keybindings.

**Comment by ypresto** [comment]
Reopen this please? (who can do it?)

I also ping-ed discord's twitter account.
https://twitter.com/yuya_presto/status/983984470016561152

**Comment by tekezo** [comment]
Is this issue still occurring in the latest beta version?
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by olegstepura** [comment]
I can confirm beta fixed the issue.

**Comment by ypresto** [comment]
I also confirmed it is fixed in the 12.0.0..! Thanks!

**Comment by ZirconiumX** [comment]
@tekezo Would you mind telling us how you fixed this, so we could also fix it in ckb-next?

**Comment by cfstras** [comment]
Still occuring on Karabiner 13.0.0 -- Some days it works, sometimes restarting Discord helps. Sometimes Discord just can't see any keys being pressed.

**Comment by arieh** [comment]
What I found that works (I do this every time I start discord):
1. Start event viewer
2. Open discord settings
3. Re-bind PTT key

I noticed that Discord ignores my Karabiner settings, but the rest of the system respects it (I bind CAPSLOCK to F16. In discord it still shows as CAPS but rest of my system recognizes F16)

**Comment by agnesnutter** [comment]
This is still an issue. If Karabiner is modifying key bindings, the keys are doubled within Discord, and then it is impossible to input.
![Screen Shot 2022-02-06 at 2 42 17 PM](https://user-images.githubusercontent.com/6315656/152698473-20c5462d-58f0-4fe3-92fb-186c067be437.png)
