### ISSUE TITLE
Caps lock issues.

### ISSUE THREAD

**Issue by a-triant** [tekezo/Karabiner-Elements#531]
I have two issues with a Caps lock.

1. The Caps lock button have a delay, when i hit it very fast it does not activates.

2. The LED light of the Caps lock turns off, if example i activate it in one application, let's say it's Safari, then i click to another application or even to a desktop then the LED turns off but the Caps lock still remain activated, another example if i have activated the Caps lock during renaming a folder or a file and after i click back to desktop or elsewhere then the same happening, this even happening during login to macOS.

Those issues are available after the 0.90.66 version, every time i have to downgrade to 0.90.66.

Thanks.

**Comment by saagarjha** [comment]
The delay for the Caps Lock is [by design](http://web.archive.org/web/20150115033359/http://support.apple.com/en-us/HT201509). You may be able to find a fix for it [here](http://apple.stackexchange.com/questions/81234/how-to-remove-caps-lock-delay-on-apple-macbook-pro-aluminum-keyboard). As for the light turning off, that's probably a bug.

**Comment by a-triant** [comment]
Thanks for the information. As i see now, that's feature with delay of the Caps Lock is for Mac notebooks only, i have a Mac mini, so that's why i never noticed this before.

**Comment by tekezo** [comment]
> The Caps lock button have a delay, when i hit it very fast it does not activates.

I added Caps Lock Delay configuration in Virtual Keyboard tab at v0.90.76.
Please set the value to zero.

> The LED light of the Caps lock turns off,

It is an issue of macOS.
(macOS does not send kCGEventFlagsChanged event even if the caps lock state was changed in such situation.)
Please file an issue to Apple BTS.

**Comment by a-triant** [comment]
Thank you!

But the LED worked fine in 0.90.66 and in every version below it.

That how it works in 0.90.66
![screen shot 2017-01-12 at 5 22 12 pm](https://cloud.githubusercontent.com/assets/22340405/21895603/fd4a3224-d8eb-11e6-902f-5a9d96470f76.png)

And below is how the Caps Lock works in 0.90.76, if i just pressing it inside the  EventViewer.
![screen shot 2017-01-12 at 5 25 51 pm](https://cloud.githubusercontent.com/assets/22340405/21895735/66877eb8-d8ec-11e6-8be1-5ca9a2fc3093.png)

And this is also 0.90.76 and if i pressing it in anywhere else, desktop(Finder) or any application, i noticed its different than in EvenViewer window.
![screen shot 2017-01-12 at 5 35 51 pm](https://cloud.githubusercontent.com/assets/22340405/21896107/d6d63b86-d8ed-11e6-841f-e4426f9d909c.png)

**Comment by tekezo** [comment]
Is your caps lock LED always turned off?

If so, please check follows:

1. Karabiner-Elements does not manipulate ignored device. Is your keyboard which has LED changed in Karabiner-Elements?
2. Karabiner-Elements uses `CGEventTap` to detect the caps lock state. Is `event_tap_manager initialized` message in Log?

```
Example of the log message

[2017-01-13 01:10:51.876] [info] [grabber] event_tap_manager initialized
```

**Comment by a-triant** [comment]
No, the LED of caps lock turns on, here i made a video of what exactly happens.
https://youtu.be/utPnTOhmb2U

Like i said in the 1st message, when i activate the caps lock and then click to another application, the light turns off but the caps lock still remain activated.

**Comment by tekezo** [comment]
Thank you for information!
I've reproduced this issue and add a workaround at v0.90.77.

Due to macOS bug and limitation, we have needed to use LED state monitor timer to avoid this issue.
So, even in v0.90.77, the caps lock LED will turn off after application switch but Karabiner corrects the LED state immediately.

**Comment by a-triant** [comment]
Thank you very much for explanation and workaround of this issue!

**Comment by teejay-87** [comment]
Hi @tekezo,

I love the caps lock delay feature on Mac. I loved it since the very first time I had a Mac.

Now I started using Karabiner-Elements (using Karabiner on my previous MBP) and noticed that Caps Lock Delay setting is by default set to 0.

Can you tell me which is the delay value macOS uses by default?

Also, can you add a feature to disable that on the internal keyboard, or at least when no external keyboard is connected?

**Comment by tekezo** [comment]
@teejay-87 The system default is 75 milliseconds. (I prefer about 200 ms.)

> Also, can you add a feature to disable that on the internal keyboard, or at least when no external keyboard is connected?

Unfortunately, the value is shared by all keyboards.
The dynamic configuration depending on connected devices is enable (e.g., using Hammerspoon), but I don't recommend it to avoid a problem around key repeat.

**Comment by teejay-87** [comment]
Thank you very much for your reply. I set it to the system default value.

**Comment by manuelalonso** [comment]
I am using Karabiner Elements 12.1.5 and I have enabled the change caps_lock to command+control+alt+shift (using shift caps_lock as caps_lock),  This used to work well, and when using shiif+caps_lock the LED would light up when enabled and light down when disabled.   Now everything works but the LED is always off.     I am not sure what line of code is needed in the karabiner.json file to restore this function, or if this is an Elements issue.  I have the manipulate LED checked in the Devices tab for the Apple Magic Keyboard with Numeric Keypad.

**Comment by mathieuades** [comment]
Hello, I also have the problem with LED : When I switch from an app to another led is switched off and then it on again. It happens on every mouse click. And it takes about 1.5 seconds to come back. 
Is there a workaround to avoid that ? 

Thanks !

**Comment by a-triant** [comment]
> Hello, I also have the problem with LED : When I switch from an app to another led is switched off and then it on again. It happens on every mouse click. And it takes about 1.5 seconds to come back.
> Is there a workaround to avoid that ? Or at least to reduce the blink time to a minimal value ?
> 
> Thanks !

In my case this issue fixed with the release of the 12.8.0 version.

**Comment by mathieuades** [comment]
> In my case this issue fixed with the release of the 12.8.0 version.

Unfortunately is still happens for me with 12.8.0 version. Have you changed something in your configuration too ?

**Comment by a-triant** [comment]
> > In my case this issue fixed with the release of the 12.8.0 version.
> 
> Unfortunately is still happens for me with 12.8.0 version. Have you changed something in your configuration too ?

No, I didn't change anything.

**Comment by Serge-Ntumba** [comment]
It looks like the 11.5.2 update actually fixed it as mentioned in a lot of forums!

GO UPDATE!



Links:

https://forums.macrumors.com/threads/11-5-2-fixes-the-caps-lock-bug.2307280/

https://www.iphonetricks.org/macos-big-sur-11-5-2-bug-fixes-for-mac/

https://forums.macrumors.com/threads/macos-big-sur-11-5-2-20g95-is-live-whats-new.2307246/#:~:text=%234-,Fixed%20the%20Caps%20Lock%20performance%20issue%20I%20was%20experiencing.,-Reactions%3A

https://forums.macrumors.com/threads/more-big-sur-bugs.2306427/page-2#:~:text=After%20some%20brief%20testing%20I%20can%20confirm%20it%20does%20seem%20to%20have%20fixed%20the%20caps%20lock%20issue.
