### ISSUE TITLE
shift+control+power not working

### ISSUE THREAD

**Issue by himazu** [tekezo/Karabiner-Elements#89]
With the following configuration, shift+control (physically caps_lock)+power to lock screen does not work.

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "right_option": "delete_forward",
                "caps_lock": "left_control"
            }
        }
    ]
}
```

**Comment by halilim** [comment]
shift+control+eject doesn't work as well, with the following config:

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "escape",
                "non_us_backslash": "grave_accent_and_tilde"
            }
        }
    ]
}
```

**Comment by kubofonista** [comment]
It is not working with any config, if there is an empty profile the problem is the same.

**Comment by oderwat** [comment]
I was cursing over sierra for removing this keyboard shortcut for the last two hours until I found this issue description.

**Comment by FlorinMotoc** [comment]
I had activated from System Preferences -> Accessibility -> Zoom -> the "Use scroll gesture with modifier keys to zoom" which allowed CTRL + Scroll to zoom screen.
Not working anymore after yesterday's update.

The day before worked ok.

Found Karabiner-Elements-0.90.29.dmg in Trash, restored, installed it. Now it is fixed :D

**Comment by princed** [comment]
More issues:
* `non_us_backslash` and `grave_accent_and_tilde` are swapped by default without any configuration
* My custom shortcuts in BetterTouchTool with PgUp and PgDown do not work as well

**Comment by NytroRST** [comment]
Still not fixed, I cannot lock my Mac (Sierra last beta).

**Comment by AndersTao** [comment]
I see the same zoom problem, and it looks like the .29 fix it for now.

The download link did not work for me, but found a link to all version:
https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files

**Comment by wwwjfy** [comment]
Though `CGPostKeyboardEvent` is deprecated, I found it fixes some problems, including the ctrl-opt-cmd-power to lock, and ctrl-opt-esc to open Force Quit window. (Seems these two are different, as with 0.90.29, the former worked, but the latter didn't)

I guess `CGPostKeyboardEvent` might be more low-level. I don't think it should be used, but it may be a hint to any solution.

```diff
diff --git a/src/core/grabber/include/manipulator/event_manipulator.hpp b/src/core/grabber/include/manipulator/event_manipulator.hpp
index 30e2381..9f68a65 100644
--- a/src/core/grabber/include/manipulator/event_manipulator.hpp
+++ b/src/core/grabber/include/manipulator/event_manipulator.hpp
@@ -563,11 +563,7 @@ private:
       // We have to post modifier key event via CGEventPost for some apps (Microsoft Remote Desktop)
       if (event_source_) {
         if (auto cg_key = krbn::types::get_cg_key(key_code)) {
-          if (auto event = CGEventCreateKeyboardEvent(event_source_, static_cast<CGKeyCode>(*cg_key), pressed)) {
-            CGEventSetFlags(event, modifier_flag_manager_.get_cg_event_flags(CGEventGetFlags(event), key_code));
-            CGEventPost(kCGHIDEventTap, event);
-            CFRelease(event);
-          }
+          CGPostKeyboardEvent((CGCharCode)0, static_cast<CGKeyCode>(*cg_key), pressed);
         }
       }

@@ -589,15 +585,7 @@ private:
   void post_key(krbn::key_code from_key_code, krbn::key_code to_key_code, bool pressed, bool repeat) {
     if (event_source_) {
       if (auto cg_key = krbn::types::get_cg_key(to_key_code)) {
-        if (auto event = CGEventCreateKeyboardEvent(event_source_, static_cast<CGKeyCode>(*cg_key), pressed)) {
-          auto event_flags = CGEventGetFlags(event);
-          CGEventFlags flags = modifier_flag_manager_.get_cg_event_flags(event_flags, to_key_code);
-          CGEventSetFlags(event, flags);
-          CGEventSetIntegerValueField(event, kCGKeyboardEventAutorepeat, repeat);
-          CGEventPost(kCGHIDEventTap, event);
-          CFRelease(event);
-        }
-
+        CGPostKeyboardEvent((CGCharCode)0, static_cast<CGKeyCode>(*cg_key), pressed);
       } else {
         auto hid_system_key = krbn::types::get_hid_system_key(to_key_code);
         auto hid_system_aux_control_button = krbn::types::get_hid_system_aux_control_button(to_key_code);
diff --git a/src/core/grabber/karabiner_grabber.xcodeproj/project.pbxproj b/src/core/grabber/karabiner_grabber.xcodeproj/project.pbxproj
index 7803484..08f8998 100644
--- a/src/core/grabber/karabiner_grabber.xcodeproj/project.pbxproj
+++ b/src/core/grabber/karabiner_grabber.xcodeproj/project.pbxproj
@@ -278,6 +278,7 @@
                3441491A1D212A1600C8ECFC /* Release */ = {
                        isa = XCBuildConfiguration;
                        buildSettings = {
+                               GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS = NO;
                                PRODUCT_NAME = karabiner_grabber;
                        };
                        name = Release;
```

**Comment by kubofonista** [comment]
Sill not working after a fix with shortcut handling

**Comment by kubofonista** [comment]
And still not working after last updates...

**Comment by kip9** [comment]
Key press itself doesn't work for me neither, but if you hold all the keys pressed for a bit (I'd guess half of second or a bit more) it does work then.

**Comment by entonio** [comment]
Please give some feedback on this. This issue is enormous. I understand you don't owe us anything, rather we owe you; I know these issues are hard to solve, but it would be nice to know whether a solution is coming at all, or if there are currently no plans/possibilities for one.

**Comment by mic773** [comment]
It's finally fixed with 0.90.67!!!!!!

**Comment by kubofonista** [comment]
It's not. Still not working on external Apple Bluetooth keyboard

**Comment by mic773** [comment]
Oh, I only tested on my 2015 Retina MacBook Pro.

**Comment by marcohamersma** [comment]
I can replicate this issue as well with my Apple Magic Keyboard. My only modification is the simple `non_us_backslash` to `grave_accent_and_tilde`. But the display sleep hotkey doesn't work.

If I untick the Magic Keyboard in the Devices tab of Karabiner the hotkey works again.

**Comment by kjoonlee** [comment]
Yeah, I can reproduce issue #89 and issue #124 with Apple Magic Keyboard too.

**Comment by mjbaldwin** [comment]
Agreed, Ctrl+Shift+Eject still not putting my display to sleep when I press it on my Magic Keyboard (Sierra, Macbook Air 1.5 yrs old, Magic Keyboard 1 yr old).

**Comment by brianweber13** [comment]
#455 and #509 are about this same problem.

**Comment by woutervanwijk** [comment]
same here, apple usb-keyboard

**Comment by architchandra** [comment]
Still not working.
